'use client';

import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

type Rule={id:string;name:string;keywords:string[];score_delta:number;target_stage:string|null;active:boolean;priority:number};
type Workflow={id:string;name:string;trigger_type:string;trigger_config:any;actions:any[];active:boolean};
type WorkflowRun={id:string;workflow_id:string;entity_type:string;entity_id:string|null;status:string;result:any;created_at:string;completed_at:string|null};

const css=`
.page{display:grid;gap:14px}.head{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;flex-wrap:wrap}.head h1{margin:5px 0}.head p{margin:0;color:#73818b;font-size:10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.panel{padding:17px;overflow:hidden}.panel h2{margin:5px 0;font-size:16px}.panel p{margin:0;color:#7d8992;font-size:9px}.form{display:grid;gap:9px;margin-top:12px}.input,.select{width:100%;box-sizing:border-box;padding:9px 10px;border:1px solid #dce5e9;border-radius:9px;background:#fff;font-size:10px}.textarea{min-height:75px;resize:vertical}.field{display:grid;gap:5px;font-size:9px;font-weight:900}.actions{display:flex;gap:7px;flex-wrap:wrap}.btn{border:1px solid #dce5e9;border-radius:9px;padding:9px 11px;background:#fff;font-size:9px;font-weight:900;cursor:pointer}.primary{background:#17202b;color:#fff;border-color:#17202b}.soft{background:#edf9f7;color:#087f7b;border-color:#d2eee9}.row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:10px;align-items:center;padding:11px 0;border-top:1px solid #edf0f3}.row:first-child{border-top:0}.row strong{font-size:10px}.row small{display:block;color:#839099;font-size:8px;margin-top:3px}.badge{display:inline-flex;padding:5px 7px;border-radius:999px;background:#eef5ff;color:#2166d1;font-size:8px;font-weight:900}.green{background:#edf9f1;color:#087443}.orange{background:#fff7e9;color:#8b5e11}.notice,.error{padding:10px 12px;border-radius:9px;font-size:10px}.notice{background:#fff;border:1px solid #dce5e9}.error{background:#fff1f2;border:1px solid #f5c8cf;color:#9f1239}.empty{padding:32px 12px;text-align:center;color:#7d8992;font-size:10px}.runs{display:grid;gap:9px;margin-top:14px}.run{border:1px solid #e6ecef;border-radius:11px;padding:12px}.run-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.run-head strong{font-size:10px}.run-meta{font-size:8px;color:#839099;margin-top:4px}.run-status{display:inline-flex;padding:5px 7px;border-radius:999px;background:#eef5ff;color:#2166d1;font-size:8px;font-weight:900;white-space:nowrap}.run-status.completed{background:#edf9f1;color:#087443}.run-status.failed{background:#fff1f2;color:#9f1239}.run-status.skipped{background:#fff7e9;color:#8b5e11}.run details{margin-top:8px}.run summary{cursor:pointer;color:#087f7b;font-size:9px;font-weight:850}.run pre{overflow:auto;max-height:260px;margin:8px 0 0;padding:10px;background:#f7fafb;border-radius:8px;font-size:9px;white-space:pre-wrap;word-break:break-word}@media(max-width:850px){.grid{grid-template-columns:1fr}.row{grid-template-columns:1fr auto}}
`;

export default function CrmAutomationPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[rules,setRules]=useState<Rule[]>([]),[workflows,setWorkflows]=useState<Workflow[]>([]),[runs,setRuns]=useState<WorkflowRun[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const[rule,setRule]=useState({name:'Buying Intent',keywords:'buy, purchase, order',score_delta:'20',target_stage:'qualified',priority:'50'});
 const[workflow,setWorkflow]=useState({name:'High Score Follow-up',trigger_type:'lead_score_changed',actionType:'create_task',actionConfig:'{"title":"Follow up with qualified lead","task_type":"follow_up","priority":"high"}'});
 async function token(){const s=(await getSupabase().auth.getSession()).data.session;if(!s)throw new Error('Session expired');return s.access_token}
 async function load(id=workspaceId){if(!id)return;setLoading(true);setError('');try{const t=await token();const r=await fetch('/api/crm/workflows?workspaceId='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+t},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to load automation.');setRules(d.rules||[]);setWorkflows(d.workflows||[]);const {data:runRows,error:runError}=await getSupabase().from('crm_workflow_runs').select('id,workflow_id,entity_type,entity_id,status,result,created_at,completed_at').eq('workspace_id',id).order('created_at',{ascending:false}).limit(30);if(runError)throw runError;setRuns((runRows||[]) as WorkflowRun[])}catch(e){setError(e instanceof Error?e.message:'Unable to load automation.')}finally{setLoading(false)}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);if(id)void load(id);else setLoading(false);const onWorkspace=(e:Event)=>{const next=(e as CustomEvent<{workspaceId?:string}>).detail?.workspaceId||'';if(next&&next!==id){id=next;setWorkspaceId(next);void load(next)}};window.addEventListener('mdsm:workspace-changed',onWorkspace);return()=>window.removeEventListener('mdsm:workspace-changed',onWorkspace)},[]);
 async function addRule(){setSaving(true);setError('');setNotice('');try{const t=await token();const r=await fetch('/api/crm/workflows',{method:'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,type:'rule',name:rule.name,keywords:rule.keywords.split(',').map(x=>x.trim()).filter(Boolean),score_delta:Number(rule.score_delta),target_stage:rule.target_stage||null,priority:Number(rule.priority)})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to add rule.');setNotice('Qualification rule added.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to add rule.')}finally{setSaving(false)}}
 async function addWorkflow(){setSaving(true);setError('');setNotice('');try{let config={};try{config=JSON.parse(workflow.actionConfig||'{}')}catch{throw new Error('Action JSON is invalid.')}const t=await token();const r=await fetch('/api/crm/workflows',{method:'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,type:'workflow',name:workflow.name,trigger_type:workflow.trigger_type,actions:[{type:workflow.actionType,config}]})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to add workflow.');setNotice('Workflow created.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to add workflow.')}finally{setSaving(false)}}
 async function toggle(type:string,id:string,active:boolean){setSaving(true);try{const t=await token();const r=await fetch('/api/crm/workflows',{method:'PATCH',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,type,id,active:!active})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to update.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update.')}finally{setSaving(false)}}
 return <AppShell title='CRM Automation'><style jsx>{css}</style><div className='page'>
  <div className='head'><div><div className='eyebrow'>CRM • AUTOMATION</div><h1>Qualification & Workflow Automation</h1><p>Create reusable lead-scoring rules and workspace workflows. These definitions are ready to run when WhatsApp/webhook events arrive.</p></div><button className='btn' onClick={()=>void load()}>↻ Refresh</button></div>
  {notice&&<div className='notice'>{notice}</div>}{error&&<div className='error'>{error}</div>}
  <div className='grid'>
   <section className='panel'><div className='eyebrow'>QUALIFICATION RULES</div><h2>Smart Lead Qualification</h2><p>Matched keywords add score and can move a lead into a stronger pipeline stage.</p><div className='form'><label className='field'>Rule name<input className='input' value={rule.name} onChange={e=>setRule({...rule,name:e.target.value})}/></label><label className='field'>Keywords<input className='input' value={rule.keywords} onChange={e=>setRule({...rule,keywords:e.target.value})}/></label><div className='grid' style={{gridTemplateColumns:'1fr 1fr'}}><label className='field'>Score +<input className='input' type='number' value={rule.score_delta} onChange={e=>setRule({...rule,score_delta:e.target.value})}/></label><label className='field'>Priority<input className='input' type='number' value={rule.priority} onChange={e=>setRule({...rule,priority:e.target.value})}/></label></div><label className='field'>Target stage<select className='select' value={rule.target_stage} onChange={e=>setRule({...rule,target_stage:e.target.value})}><option value=''>Keep stage</option><option value='qualified'>Qualified</option><option value='proposal'>Proposal</option><option value='negotiation'>Negotiation</option></select></label><button className='btn primary' disabled={saving} onClick={()=>void addRule()}>Add Qualification Rule</button></div><div style={{marginTop:13}}>{loading?<div className='empty'>Loading rules…</div>:rules.length?rules.map(r=><div className='row' key={r.id}><div><strong>{r.name}</strong><small>{r.keywords.join(', ')} · +{r.score_delta} score</small></div><span className={'badge '+(r.active?'green':'orange')}>{r.active?'ACTIVE':'PAUSED'}</span><button className='btn' disabled={saving} onClick={()=>void toggle('rule',r.id,r.active)}>{r.active?'Pause':'Activate'}</button></div>):<div className='empty'>No rules yet.</div>}</div></section>
   <section className='panel'><div className='eyebrow'>CUSTOM WORKFLOWS</div><h2>Workflow Automation</h2><p>Connect events to reusable actions such as tasks, stage changes and product suggestions.</p><div className='form'><label className='field'>Workflow name<input className='input' value={workflow.name} onChange={e=>setWorkflow({...workflow,name:e.target.value})}/></label><label className='field'>Trigger<select className='select' value={workflow.trigger_type} onChange={e=>setWorkflow({...workflow,trigger_type:e.target.value})}><option value='lead_created'>Lead created</option><option value='lead_score_changed'>Lead score changed</option><option value='whatsapp_message'>WhatsApp message</option><option value='task_due'>Task due</option></select></label><label className='field'>Action<select className='select' value={workflow.actionType} onChange={e=>setWorkflow({...workflow,actionType:e.target.value})}><option value='create_task'>Create task</option><option value='set_stage'>Set lead stage</option><option value='send_whatsapp_template'>Send WhatsApp template</option><option value='suggest_products'>Suggest products</option></select></label><label className='field'>Action configuration (JSON)<textarea className='input textarea' value={workflow.actionConfig} onChange={e=>setWorkflow({...workflow,actionConfig:e.target.value})}/></label><button className='btn primary' disabled={saving} onClick={()=>void addWorkflow()}>Create Workflow</button></div><div style={{marginTop:13}}>{loading?<div className='empty'>Loading workflows…</div>:workflows.length?workflows.map(w=><div className='row' key={w.id}><div><strong>{w.name}</strong><small>{w.trigger_type} · {(w.actions||[]).map(a=>a.type).join(', ')||'No actions'}</small></div><span className={'badge '+(w.active?'green':'orange')}>{w.active?'ACTIVE':'PAUSED'}</span><button className='btn' disabled={saving} onClick={()=>void toggle('workflow',w.id,w.active)}>{w.active?'Pause':'Activate'}</button></div>):<div className='empty'>No workflows yet.</div>}</div></section>
  </div>
  <section className='panel'><div className='head'><div><div className='eyebrow'>EXECUTION HISTORY</div><h2>Recent Workflow Runs</h2><p>Workspace-specific automation results, including the daily task-due scheduler.</p></div><button className='btn' onClick={()=>void load()} disabled={loading}>↻ Refresh history</button></div><div className='runs'>{loading?<div className='empty'>Loading execution history…</div>:runs.length?runs.map(run=>{const name=workflows.find(w=>w.id===run.workflow_id)?.name||'Workflow '+run.workflow_id.slice(0,8);const status=String(run.status||'unknown').toLowerCase();return <article className='run' key={run.id}><div className='run-head'><div><strong>{name}</strong><div className='run-meta'>{run.result?.trigger||run.entity_type} · {run.entity_type==='crm_task'?'Task':'Lead'} ID: {run.entity_id||'—'}</div><div className='run-meta'>{run.created_at?new Date(run.created_at).toLocaleString():''}{run.completed_at?' · Completed '+new Date(run.completed_at).toLocaleString():''}</div></div><span className={'run-status '+status}>{status.toUpperCase()}</span></div><details><summary>View execution details</summary><pre>{JSON.stringify(run.result||{},null,2)}</pre></details></article>}):<div className='empty'>No workflow executions recorded for this workspace yet.</div>}</div></section>
 </div></AppShell>
}