'use client';
import {useEffect,useState} from 'react';
import AppShell from '../components/AppShell';
type Post={id:string;caption:string;scheduled_for:string;status:string;account_ids:string[];last_error:string|null};
export default function CalendarPage(){const[id,setId]=useState(''),[date,setDate]=useState(()=>new Date().toISOString().slice(0,10)),[posts,setPosts]=useState<Post[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function authFetch(workspace:string,options:RequestInit={}){const {createClient}=await import('@supabase/supabase-js');const c=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const {data:{session}}=await c.auth.getSession();if(!session?.access_token)throw Error('Your session has expired.');return fetch(`/api/scheduled-posts?brandId=${encodeURIComponent(workspace)}`,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${session.access_token}`}})}
 async function load(workspace:string){setLoading(true);setError('');try{const r=await authFetch(workspace),d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load scheduled posts.');setPosts(d.posts||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load calendar')}finally{setLoading(false)}}
 useEffect(()=>{const saved=localStorage.getItem('mdsm:selectedWorkspaceId')||'';if(!saved){location.href='/dashboard';return}setId(saved);load(saved)},[]);
 const openPost=()=>id&&(location.href=`/dashboard/publish?brandId=${encodeURIComponent(id)}&scheduledDate=${encodeURIComponent(date)}`);
 async function cancel(postId:string){try{const {createClient}=await import('@supabase/supabase-js');const c=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const {data:{session}}=await c.auth.getSession();if(!session?.access_token)throw Error('Your session has expired.');const r=await fetch(`/api/scheduled-posts?id=${encodeURIComponent(postId)}`,{method:'DELETE',headers:{Authorization:`Bearer ${session.access_token}`}});if(!r.ok){const d=await r.json();throw Error(d.error||'Unable to cancel post.')}await load(id)}catch(e){setError(e instanceof Error?e.message:'Unable to cancel post.')}}
 const visible=posts.filter(p=>p.scheduled_for.slice(0,10)===date);
 return <AppShell title="Calendar"><style jsx>{`.page{max-width:1100px;margin:auto}.head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.ey{font-size:10px;font-weight:900;letter-spacing:.16em;color:#078b87}.head h1{margin:6px 0;font-size:36px;letter-spacing:-.04em}.head p{margin:0;color:#7b8794;font-size:12px}.panel{background:#fff;border:1px solid #e2e9ed;border-radius:20px;padding:24px}.row{display:flex;justify-content:space-between;gap:16px;align-items:center}.list{display:grid;gap:10px;margin-top:18px}.item{border:1px solid #e4eaee;border-radius:14px;padding:14px;display:flex;justify-content:space-between;gap:15px;align-items:center}.meta{font-size:10px;color:#7b8794;margin-top:5px}.badge{font-size:9px;font-weight:900;padding:6px 8px;border-radius:999px;background:#edf9f1;color:#087443}.btn{border:0;border-radius:10px;padding:10px 13px;font-size:11px;font-weight:900;cursor:pointer}.primary{background:#078b87;color:#fff}.danger{background:#fff0f0;color:#b42318}.empty{text-align:center;padding:55px 20px;color:#87939d}.err{padding:12px;border-radius:10px;background:#fff0f0;color:#b42318;font-size:11px;margin-bottom:14px}@media(max-width:700px){.head,.row,.item{align-items:flex-start;flex-direction:column}}`}</style><div className="page"><div className="head"><div><span className="ey">PLANNING</span><h1>Content Calendar</h1><p>Plan and review scheduled content for this workspace.</p></div><button className="btn primary" onClick={openPost}>＋ Schedule Post</button></div>{error&&<div className="err">⚠ {error}</div>}<section className="panel"><div className="row"><div><b>Workspace Planner</b><div className="meta">{loading?'Loading scheduled posts…':`${visible.length} post${visible.length===1?'':'s'} on this date`}</div></div><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div>{loading?<div className="empty">Loading…</div>:visible.length?<div className="list">{visible.map(p=><div className="item" key={p.id}><div><b>{p.caption||'Untitled post'}</b><div className="meta">{new Date(p.scheduled_for).toLocaleString()} · {p.account_ids.length} account(s)</div>{p.last_error&&<div className="meta">Error: {p.last_error}</div>}</div><div><span className="badge">{p.status}</span>{(p.status==='scheduled'||p.status==='failed'||p.status==='draft')&&<button className="btn danger" style={{marginLeft:8}} onClick={()=>cancel(p.id)}>Cancel</button>}</div></div>)}</div>:<div className="empty"><h3>No scheduled posts</h3><p>Create content for this date and it will appear here.</p><button className="btn primary" onClick={openPost}>＋ Create Scheduled Post</button></div>}</section></div></AppShell>}
