'use client';

import {useEffect,useMemo,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

type Lead={id:string;name:string|null;email:string|null;phone:string|null;message:string|null;source:string;created_at:string};
type Message={id:string;name:string|null;email:string|null;phone:string|null;subject:string|null;message:string|null;created_at:string};

const css='.page{display:grid;gap:14px}.head{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;flex-wrap:wrap}.head h1{margin:5px 0}.head p{margin:0;color:#73818b;font-size:10px}.btn{border:1px solid #dce5e9;border-radius:9px;padding:9px 11px;background:#fff;font-size:9px;font-weight:900;cursor:pointer}.error{padding:10px 12px;background:#fff1f2;border:1px solid #f5c8cf;color:#9f1239;border-radius:10px;font-size:10px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.stat{padding:14px}.stat span{display:block;color:#77848d;font-size:8px;text-transform:uppercase;letter-spacing:.08em;font-weight:900}.stat strong{display:block;font-size:23px;margin-top:7px}.stat small{color:#8b969e;font-size:8px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.panel{overflow:hidden}.section-head{padding:15px 17px;border-bottom:1px solid #edf0f3}.section-head h2{margin:4px 0;font-size:15px}.section-head p{margin:0;color:#7d8992;font-size:9px}.searchbar{padding:11px 17px;border-bottom:1px solid #edf0f3}.search{width:100%;padding:9px 10px;border:1px solid #dce5e9;border-radius:9px;font-size:10px}.list{padding:0 17px 12px}.row{padding:12px 0;border-top:1px solid #edf0f3}.row:first-child{border-top:0}.row strong{font-size:10px}.row small{display:block;color:#839099;font-size:8px;margin-top:4px;line-height:1.5}.tag{display:inline-flex;padding:5px 7px;background:#eef5ff;color:#2166d1;border-radius:999px;font-size:8px;font-weight:900;margin-top:6px}.empty{padding:40px 15px;text-align:center;color:#7c8891;font-size:10px}.card-actions{display:flex;gap:7px;margin-top:8px}.card-actions a{font-size:9px;font-weight:900;color:#2166d1;text-decoration:none}@media(max-width:800px){.grid{grid-template-columns:1fr}.stats{grid-template-columns:1fr 1fr}}';

export default function DigitalCardLeadsPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[leads,setLeads]=useState<Lead[]>([]),[messages,setMessages]=useState<Message[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[error,setError]=useState('');
 async function token(){const s=(await getSupabase().auth.getSession()).data.session;if(!s)throw new Error('Session expired');return s.access_token}
 async function load(id=workspaceId){if(!id)return;setLoading(true);setError('');try{const t=await token();const r=await fetch('/api/digital-card/leads?workspaceId='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+t},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to load enquiries.');setLeads(d.leads||[]);setMessages(d.messages||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load enquiries.')}finally{setLoading(false)}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);if(id)void load(id);else setLoading(false);const onWorkspace=(e:Event)=>{const next=(e as CustomEvent<{workspaceId?:string}>).detail?.workspaceId||'';if(next&&next!==id){id=next;setWorkspaceId(next);void load(next)}};window.addEventListener('mdsm:workspace-changed',onWorkspace);return()=>window.removeEventListener('mdsm:workspace-changed',onWorkspace)},[]);
 const q=query.toLowerCase().trim();const lf=useMemo(()=>leads.filter(x=>!q||[x.name,x.email,x.phone,x.message].some(v=>String(v||'').toLowerCase().includes(q))),[leads,q]);const mf=useMemo(()=>messages.filter(x=>!q||[x.name,x.email,x.phone,x.subject,x.message].some(v=>String(v||'').toLowerCase().includes(q))),[messages,q]);
 return <AppShell title='Digital Card Leads'><style jsx>{css}</style><div className='page'>
  <div className='head'><div><div className='eyebrow'>DIGITAL CARD • LEADS & CONTACTS</div><h1>Leads & Contact Enquiries</h1><p>Every public Digital Card lead-capture and contact-form submission is visible here for the selected workspace.</p></div><div><button className='btn' onClick={()=>void load()}>↻ Refresh</button></div></div>
  {error&&<div className='error'>{error}</div>}
  <div className='stats'><article className='panel stat'><span>Lead Captures</span><strong>{loading?'—':leads.length}</strong><small>Public lead forms</small></article><article className='panel stat'><span>Contact Messages</span><strong>{loading?'—':messages.length}</strong><small>Public contact forms</small></article><article className='panel stat'><span>Total Enquiries</span><strong>{loading?'—':leads.length+messages.length}</strong><small>Workspace enquiries</small></article></div>
  <section className='panel'><div className='section-head'><div className='eyebrow'>SEARCH</div><h2>Find an enquiry</h2></div><div className='searchbar'><input className='search' value={query} onChange={e=>setQuery(e.target.value)} placeholder='Search name, email, phone, subject or message…'/></div></section>
  <div className='grid'><section className='panel'><div className='section-head'><div className='eyebrow'>LEAD CAPTURE</div><h2>Leads</h2><p>Ready to move into CRM or WhatsApp follow-up workflows.</p></div><div className='list'>{loading?<div className='empty'>Loading leads…</div>:lf.length?lf.map(x=><article className='row' key={x.id}><strong>{x.name||'Unnamed lead'}</strong><small>{[x.email,x.phone].filter(Boolean).join(' · ')||'No contact details'}<br/>{x.message||'No message'}</small><span className='tag'>{x.source||'digital_card'}</span><div className='card-actions'>{x.phone&&<a href={'tel:'+x.phone}>Call</a>}{x.email&&<a href={'mailto:'+x.email}>Email</a>}</div></article>):<div className='empty'>No lead captures yet.</div>}</div></section>
  <section className='panel'><div className='section-head'><div className='eyebrow'>CONTACT FORM</div><h2>Messages</h2><p>Customer contact enquiries from the public Digital Card.</p></div><div className='list'>{loading?<div className='empty'>Loading messages…</div>:mf.length?mf.map(x=><article className='row' key={x.id}><strong>{x.name||'Unnamed contact'}{x.subject?' · '+x.subject:''}</strong><small>{[x.email,x.phone].filter(Boolean).join(' · ')||'No contact details'}<br/>{x.message||'No message'}</small><span className='tag'>{new Date(x.created_at).toLocaleString()}</span><div className='card-actions'>{x.phone&&<a href={'tel:'+x.phone}>Call</a>}{x.email&&<a href={'mailto:'+x.email}>Email</a>}</div></article>):<div className='empty'>No contact messages yet.</div>}</div></section></div>
 </div></AppShell>
}