'use client';
import {useEffect,useState} from 'react';

const css=`
.page{min-height:100vh;background:linear-gradient(135deg,#eff8ff,#f8fbfb);padding:26px 14px 60px;color:#17202b}.shell{max-width:900px;margin:auto;display:grid;gap:14px}.card{background:#fff;border:1px solid #e1e8ec;border-radius:22px;padding:18px;box-shadow:0 18px 55px rgba(15,23,42,.08)}.cover{height:210px;border-radius:17px;overflow:hidden;background:#dfeff3}.cover img{width:100%;height:100%;object-fit:cover}.identity{display:flex;gap:14px;align-items:flex-end;margin-top:-38px;padding:0 12px;position:relative}.avatar{width:92px;height:92px;border-radius:24px;border:4px solid #fff;background:#eef5ff;display:grid;place-items:center;overflow:hidden;font-weight:950;font-size:24px;color:#2168c9}.avatar img{width:100%;height:100%;object-fit:cover}.hero h1{margin:12px 0 3px;font-size:27px}.hero p{margin:4px 0;color:#667085;font-size:11px;line-height:1.55}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}.btn{border:1px solid #dce5e9;border-radius:11px;padding:10px 12px;background:#fff;color:#24313b;font-size:10px;font-weight:900;cursor:pointer}.primary{background:#2168c9;color:#fff;border-color:#2168c9}.green{background:#edf9f4;color:#087f5c;border-color:#d0efe1}.section h2{margin:0 0 5px;font-size:16px}.section p{margin:0;color:#7b8792;font-size:10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.list{display:grid;gap:8px;margin-top:12px}.item{padding:12px;border:1px solid #e5eaee;border-radius:11px;background:#fbfcfd}.item strong{font-size:10px}.item small{display:block;color:#7d8992;font-size:9px;line-height:1.45;margin-top:4px}.price{float:right;font-weight:950;font-size:10px}.socials{display:flex;gap:7px;flex-wrap:wrap;margin-top:11px}.social{padding:7px 9px;background:#f1f5f7;border-radius:999px;font-size:9px;font-weight:900}.form{display:grid;gap:8px;margin-top:12px}.input{border:1px solid #dce5e9;border-radius:9px;padding:10px 11px;font-size:10px}.textarea{min-height:75px;resize:vertical}.msg{padding:10px 12px;border-radius:10px;background:#edf9f4;color:#087f5c;font-size:10px}.error{padding:10px 12px;border-radius:10px;background:#fff1f2;color:#9f1239;font-size:10px}.muted{color:#7d8992;font-size:10px}@media(max-width:700px){.grid{grid-template-columns:1fr}.cover{height:160px}}
`;
export default function DigitalCardPublic({params}:{params:{slug:string}}){
 const[card,setCard]=useState<any>(null),[data,setData]=useState<any>({contacts:[],socialLinks:[],services:[],testimonials:[],embeds:[],payments:[]}),[loading,setLoading]=useState(true),[formType,setFormType]=useState<'lead'|'contact'>('lead'),[form,setForm]=useState({name:'',email:'',phone:'',subject:'',message:''}),[msg,setMsg]=useState(''),[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const r=await fetch('/api/public/digital-card?slug='+encodeURIComponent(params.slug),{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Card not found.');setCard(d.card);setData(d)}catch(e){setError(e instanceof Error?e.message:'Card not found.')}finally{setLoading(false)}})()},[params.slug]);
 async function submit(){setMsg('');setError('');try{const r=await fetch('/api/public/digital-card',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug:params.slug,type:formType,...form})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to submit.');setMsg('Thank you. Your request has been submitted.');setForm({name:'',email:'',phone:'',subject:'',message:''})}catch(e){setError(e instanceof Error?e.message:'Unable to submit.')}} 
 if(loading)return <main className='page'><div className='shell'><div className='card muted'>Loading digital card…</div></div></main>;
 if(!card)return <main className='page'><div className='shell'><div className='card error'>{error||'Card not found.'}</div></div></main>;
 return <main className='page'><style>{css}</style><div className='shell'>
  <section className='card hero'><div className='cover'>{card.cover_image_url&&<img src={card.cover_image_url} alt=''/ >}</div><div className='identity'><div className='avatar'>{card.profile_picture_url?<img src={card.profile_picture_url} alt=''/ >:(card.business_name||card.full_name||'DC').slice(0,2).toUpperCase()}</div></div><h1>{card.full_name||card.business_name}</h1><p><strong>{card.business_name}</strong></p><p>{card.bio}</p><div className='actions'>{card.payment_url&&<a className='btn primary' href={card.payment_url} target='_blank' rel='noreferrer'>Payment</a>}{card.lead_capture_enabled&&<button className='btn green' onClick={()=>{setFormType('lead');document.getElementById('forms')?.scrollIntoView({behavior:'smooth'})}}>Get in Touch</button>}</div>{data.contacts.length>0&&<div className='list'>{data.contacts.map((x:any,i:number)=><div className='item' key={i}><strong>{x.label}</strong><small>{x.value}</small></div>)}</div>}{data.socialLinks.length>0&&<div className='socials'>{data.socialLinks.map((x:any,i:number)=><a className='social' key={i} href={x.url} target='_blank' rel='noreferrer'>{x.platform}</a>)}</div>}</section>
  <div className='grid'><section className='card section'><h2>About Us</h2><p>{card.about_us||'About this business.'}</p>{card.offline_content&&<div className='item' style={{marginTop:12}}><strong>Offline Content</strong><small>{card.offline_content}</small></div>}</section><section className='card section'><h2>Services</h2>{data.services.length?<div className='list'>{data.services.map((x:any,i:number)=><div className='item' key={i}><span className='price'>{x.price!=null?'₹'+x.price:''}</span><strong>{x.name}</strong><small>{x.description}</small></div>)}</div>:<p style={{marginTop:8}}>No services listed.</p>}</section></div>
  <div className='grid'><section className='card section'><h2>Testimonials</h2>{data.testimonials.length?<div className='list'>{data.testimonials.map((x:any,i:number)=><div className='item' key={i}><strong>{x.customer_name} · {'★'.repeat(x.rating||0)}</strong><small>{x.quote}</small></div>)}</div>:<p style={{marginTop:8}}>No testimonials yet.</p>}</section><section className='card section' id='forms'><h2>{formType==='lead'?'Lead Capture Form':'Contact Us Form'}</h2><p>Send your enquiry directly to this business.</p><div className='actions'><button className='btn' onClick={()=>setFormType('lead')}>Lead</button><button className='btn' onClick={()=>setFormType('contact')}>Contact</button></div><div className='form'><input className='input' placeholder='Name' value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className='input' placeholder='Email' value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className='input' placeholder='Phone' value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/>{formType==='contact'&&<input className='input' placeholder='Subject' value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/>}<textarea className='input textarea' placeholder='Message' value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><button className='btn primary' onClick={()=>void submit()}>Submit</button></div>{msg&&<div className='msg'>{msg}</div>}{error&&<div className='error'>{error}</div>}</section></div>
 </div></main>
}