'use client';
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

export default function MarketComparisonPage(){
 const[avg,setAvg]=useState<number|null>(null),[benchmark,setBenchmark]=useState(4.5),[category,setCategory]=useState('General service business');
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}if(!id)return;void(async()=>{const s=(await getSupabase().auth.getSession()).data.session;if(!s)return;const r=await fetch('/api/google/business/analytics?workspaceId='+encodeURIComponent(id)+'&days=365',{headers:{Authorization:'Bearer '+s.access_token},cache:'no-store'});const d=await r.json().catch(()=>({}));if(r.ok)setAvg(d?.metrics?.averageRating==null?null:Number(d.metrics.averageRating))})()},[]);
 const gap=avg==null?null:Math.round((avg-benchmark)*100)/100;
 return <AppShell title='Market Comparison'><style jsx>{".page{display:grid;gap:14px}.panel{padding:18px}.hero h1{margin:5px 0}.note{font-size:10px;color:#667085;line-height:1.6}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.big{font-size:36px;font-weight:950;margin-top:8px}.select,.input{width:100%;border:1px solid #dbe4e8;border-radius:10px;padding:10px;background:#fff;font-size:10px}.pill{display:inline-block;padding:7px 9px;border-radius:999px;background:#edf8f7;color:#087f7b;font-size:9px;font-weight:900;margin-top:10px}.btn{border:1px solid #dbe4e8;background:#fff;border-radius:9px;padding:9px 11px;font-size:9px;font-weight:900;cursor:pointer}@media(max-width:750px){.grid{grid-template-columns:1fr}}"} </style><div className='page'><section className='panel hero'><div className='eyebrow'>MARKET COMPARISON</div><h1>Reputation Benchmark</h1><p className='note'>Compare the imported workspace average to an editable benchmark. This is not a live competitor feed.</p></section><div className='grid'><section className='panel'><div className='eyebrow'>YOUR WORKSPACE</div><div className='big'>{avg==null?'—':avg.toFixed(2)+'/5'}</div><p className='note'>365-day imported review average</p></section><section className='panel'><div className='eyebrow'>BENCHMARK</div><label className='note'>Category<select className='select' value={category} onChange={e=>setCategory(e.target.value)} style={{marginTop:5}}><option>General service business</option><option>Healthcare</option><option>Home services</option><option>Retail</option><option>Restaurant</option></select></label><input className='input' type='number' min='1' max='5' step='.01' value={benchmark} onChange={e=>setBenchmark(Number(e.target.value))} style={{marginTop:8}}/><div className='pill'>{gap==null?'Waiting for review data':gap>=0?'Above benchmark by '+gap.toFixed(2)+' pts':'Below benchmark by '+Math.abs(gap).toFixed(2)+' pts'}</div></section></div><section className='panel'><div className='eyebrow'>NEXT</div><p className='note'>Run Rating Improvement Suggestions and AI Business Insights to turn the comparison into actions.</p><button className='btn' onClick={()=>location.href='/dashboard/gmb/ai'}>Open Reputation AI →</button></section></div></AppShell>
}
