'use client';
import { useEffect, useState, type ReactNode } from 'react';
import { getSupabase } from '../../../lib/supabase-browser';

const nav=[['Dashboard','⌂','/dashboard'],['Accounts','◎','/dashboard/accounts'],['Create Post','✎','/dashboard/publish'],['Calendar','□','/dashboard/calendar'],['Analytics','▥','/dashboard/analytics'],['Media Library','▧','/dashboard/media'],['Settings','⚙','/dashboard/settings']];

type Workspace={id:string;name:string};

export default function AppShell({children,title='Dashboard'}:{children:ReactNode;title?:string}){
  const[open,setOpen]=useState(false),[email,setEmail]=useState(''),[workspaces,setWorkspaces]=useState<Workspace[]|null>(null);
  useEffect(()=>{(async()=>{const supabase=getSupabase();const{data}=await supabase.auth.getUser();if(!data.user){location.href='/login';return}setEmail(data.user.email||'');const session=(await supabase.auth.getSession()).data.session;const r=await fetch('/api/brands',{headers:{Authorization:`Bearer ${session?.access_token||''}`},cache:'no-store'});const d=await r.json().catch(()=>({}));setWorkspaces(r.ok?(d.brands||[]):[]);})()},[]);
  async function signOut(){await getSupabase().auth.signOut();location.href='/login'}
  if(workspaces===null)return <main className="auth-page"><div className="muted">Loading Social Media Manager…</div></main>;
  if(workspaces.length===0)return <main className="auth-page"><section className="auth-card" style={{maxWidth:520,textAlign:'center'}}><div className="brand">SOCIAL MEDIA MANAGER</div><h1>Welcome to Social Media Manager</h1><p className="muted">Create your first workspace to keep accounts, posts, analytics and publishing organized in one place.</p><button className="primary-btn" onClick={()=>location.href='/dashboard/brands'}>＋ Create Workspace</button><button className="text-btn" style={{display:'block',margin:'14px auto 0'}} onClick={signOut}>Sign out</button></section></main>;
  return <main className="app-shell"><div className={`sidebar-backdrop ${open?'show':''}`} onClick={()=>setOpen(false)}/><aside className={`sidebar ${open?'mobile-open':''}`}><div className="logo-block"><div className="logo-mark">MD</div><div className="logo-title">MD<span>HYGIENE</span><small>SOCIAL MANAGER</small></div><button className="drawer-close" onClick={()=>setOpen(false)}>×</button></div><nav>{nav.map(([label,icon,href])=><button key={label} className={`nav-item ${title===label?'active':''}`} onClick={()=>{setOpen(false);location.href=href}}><b>{icon}</b><span>{label}</span></button>)}</nav><div className="side-user"><div className="user-avatar">MD</div><div><strong>Social Manager</strong><small>{email||'Admin'}</small></div><button onClick={signOut}>↪</button></div></aside><section className="main-shell"><header className="main-header"><button className="menu-btn" onClick={()=>setOpen(true)}>☰</button><strong>{title}</strong><div className="search-box">⌕ <span>Search anything...</span><kbd>Ctrl K</kbd></div><div className="header-actions"><button aria-label="Notifications">♢</button><button className="header-profile" onClick={()=>location.href='/dashboard/brands'}><div className="mini-logo">WS</div><strong>Workspace</strong><span>⌄</span></button></div></header><div className="page-content">{children}</div></section></main>
}
