'use client';

import { useEffect, useMemo, useState } from 'react';
import AppShell from '../../components/AppShell';
import { getSupabase } from '../../../../lib/supabase-browser';

type Member={id:string;user_id:string;employee_id:string;role:string;active:boolean;profiles?:{full_name?:string}|null};
type Permission={id?:string;user_id:string;workspace_id?:string;module:string;can_view:boolean;can_create:boolean;can_edit:boolean;can_submit:boolean;can_approve:boolean;can_publish:boolean;can_manage:boolean};
type Access={role:string;is_owner_or_admin:boolean};

const modules=[
 ['dashboard','Dashboard'],['content','Content / Create Post'],['creative','Creative Intelligence'],['drafts','Drafts'],['calendar','Calendar'],['approval','Approvals'],['publishing','Publishing History'],['analytics','Analytics'],['social_accounts','Social Accounts'],['team','Team Management']
] as const;
const actions=['can_view','can_create','can_edit','can_submit','can_approve','can_publish','can_manage'] as const;
const actionLabels:Record<string,string>={can_view:'View',can_create:'Create',can_edit:'Edit',can_submit:'Submit',can_approve:'Approve',can_publish:'Publish',can_manage:'Manage'};
const blankPermissions=(userId:string,module:string):Permission=>({user_id:userId,module,can_view:false,can_create:false,can_edit:false,can_submit:false,can_approve:false,can_publish:false,can_manage:false});

export default function EmployeeAccessPage(){
 const[id,setId]=useState(''),[members,setMembers]=useState<Member[]>([]),[selected,setSelected]=useState(''),[access,setAccess]=useState<Access|null>(null),[permissions,setPermissions]=useState<Record<string,Permission>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const selectedMember=useMemo(()=>members.find(m=>m.user_id===selected)||null,[members,selected]);
 async function token(){const s=(await getSupabase().auth.getSession()).data.session;if(!s)throw new Error('Session expired');return s.access_token}
 async function load(){
  setLoading(true);setMessage('');
  try{
   const saved=localStorage.getItem('mdsm:selectedWorkspaceId')||''; if(!saved){location.href='/dashboard';return}
   setId(saved);const t=await token();
   const accessRes=await fetch(`/api/workspace-access?workspace_id=${encodeURIComponent(saved)}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const ad=await accessRes.json();
   if(!accessRes.ok||!ad.is_owner_or_admin){location.href='/dashboard';return} setAccess(ad);
   const mRes=await fetch(`/api/workspace-employees?workspace_id=${encodeURIComponent(saved)}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const md=await mRes.json();
   if(!mRes.ok)throw new Error(md?.error||'Unable to load employees.');setMembers(md.members||[]);
  }catch(e){setMessage(e instanceof Error?e.message:'Unable to load employee access.');}finally{setLoading(false)}
 }
 async function loadPermissions(userId:string){
  setSelected(userId);setMessage('');try{const t=await token();const r=await fetch(`/api/admin/permissions?workspace_id=${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Unable to load permissions.');const next:Record<string,Permission>={};(d.permissions||[]).filter((p:Permission)=>p.user_id===userId).forEach((p:Permission)=>{next[p.module]=p});setPermissions(next);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load permissions.');}}
 function toggle(module:string,action:string){setPermissions(cur=>{const base=cur[module]||blankPermissions(selected,module);return {...cur,[module]:{...base,[action]:!base[action as keyof Permission]}}})}
 async function saveAll(){if(!selectedMember)return;setSaving(true);setMessage('');try{const t=await token();for(const [module,label] of modules){const p=permissions[module]||blankPermissions(selectedMember.user_id,module);const permissionPayload={module,can_view:p.can_view,can_create:p.can_create,can_edit:p.can_edit,can_submit:p.can_submit,can_approve:p.can_approve,can_publish:p.can_publish,can_manage:p.can_manage};const r=await fetch('/api/admin/permissions',{method:'PUT',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({workspace_id:id,user_id:selectedMember.user_id,...permissionPayload})});const d=await r.json();if(!r.ok)throw new Error(d?.error||`Unable to save ${label}.`)}setMessage('Employee access saved successfully.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save employee access.')}finally{setSaving(false)}}
 useEffect(()=>{void load()},[]);
 if(loading)return <AppShell title="Settings"><style jsx>{styles}</style><div className="access-loading"><div className="spinner"/><span>Loading employee access…</span></div></AppShell>;
 return <AppShell title="Settings"><style jsx>{styles}</style>
  <div className="access-page">
   <header className="hero"><div><span className="eyebrow">TEAM ACCESS</span><h1>Employee Access</h1><p>Set precise module permissions for each active team member. Changes apply only to the selected workspace.</p></div><div className="hero-note"><strong>{members.filter(m=>m.role!=='owner'&&m.active).length}</strong><span>active team members</span></div></header>
   {message&&<div className="notice" role="status"><span className="notice-dot"/>{message}</div>}
   <div className="access-grid">
    <aside className="members-card panel"><div className="panel-head"><div><h2>Team Members</h2><p>Select a member to edit access.</p></div></div><div className="member-list">{members.filter(m=>m.role!=='owner'&&m.active).map(m=><button key={m.user_id} className={`member-row ${selected===m.user_id?'active':''}`} onClick={()=>void loadPermissions(m.user_id)}><span className="avatar">{(m.profiles?.full_name||m.employee_id).slice(0,2).toUpperCase()}</span><span className="member-copy"><strong>{m.profiles?.full_name||m.employee_id}</strong><small>{m.employee_id} · {m.role}</small></span><span className="chevron">›</span></button>)}{members.filter(m=>m.role!=='owner'&&m.active).length===0&&<div className="empty"><strong>No active employees</strong><span>Create or activate a team member first.</span></div>}</div></aside>
    <section className="permissions-card panel">{!selectedMember?<div className="empty-state"><div className="empty-icon">✓</div><h2>Select an employee</h2><p>Choose a team member from the left to configure their permissions.</p></div>:<>
      <div className="selected-head"><div className="selected-person"><div className="avatar large">{(selectedMember.profiles?.full_name||selectedMember.employee_id).slice(0,2).toUpperCase()}</div><div><span className="eyebrow">SELECTED MEMBER</span><h2>{selectedMember.profiles?.full_name||selectedMember.employee_id}</h2><p>{selectedMember.employee_id} · {selectedMember.role}</p></div></div><button className="save-btn" onClick={()=>void saveAll()} disabled={saving}>{saving?'Saving…':'Save Access'}</button></div>
      <div className="matrix-wrap"><table className="matrix"><thead><tr><th className="module-col">Module</th>{actions.map(a=><th key={a}>{actionLabels[a]}</th>)}</tr></thead><tbody>{modules.map(([module,label])=><tr key={module}><td className="module-cell"><strong>{label}</strong><span>{module==='content'?'Posts and content creation':module==='social_accounts'?'Connected social channels':'Workspace module'}</span></td>{actions.map(a=><td key={a} className="check-cell"><label className="check"><input type="checkbox" checked={Boolean(permissions[module]?.[a])} onChange={()=>toggle(module,a)} aria-label={`${label} ${actionLabels[a]}`}/><span/></label></td>)}</tr>)}</tbody></table></div>
      <div className="footer-note"><span>Workspace Settings is not assignable here.</span><strong>Owner / Admin only</strong></div>
    </>}</section>
   </div>
  </div>
 </AppShell>;
}

const styles=`
.access-page{min-height:100%;padding-bottom:28px}.access-loading{min-height:320px;display:grid;place-items:center;gap:10px;color:#66727d;font-size:13px}.spinner{width:24px;height:24px;border:3px solid #dbe7e9;border-top-color:#078b87;border-radius:50%;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
.hero{display:flex;justify-content:space-between;gap:24px;align-items:flex-end;margin-bottom:22px}.hero h1{margin:6px 0 8px;font-size:32px;letter-spacing:-.035em}.hero p{margin:0;color:#6f7c87;max-width:720px;line-height:1.6;font-size:13px}.hero-note{display:grid;gap:2px;text-align:right;padding:12px 16px;border:1px solid #dfe8ea;background:#fff;border-radius:14px;min-width:120px}.hero-note strong{font-size:22px;color:#17202b}.hero-note span{font-size:10px;color:#73808b;font-weight:800;text-transform:uppercase;letter-spacing:.08em}
.eyebrow{font-size:10px;letter-spacing:.12em;color:#078b87;font-weight:950}.notice{display:flex;align-items:center;gap:9px;margin:0 0 16px;padding:11px 13px;border:1px solid #d7ebe8;background:#f3fbfa;color:#1e5e59;border-radius:12px;font-size:12px;font-weight:750}.notice-dot{width:7px;height:7px;border-radius:50%;background:#078b87;flex:none}.access-grid{display:grid;grid-template-columns:290px minmax(0,1fr);gap:18px;align-items:start}.panel{background:#fff;border:1px solid #e1eaed;border-radius:18px;box-shadow:0 10px 30px rgba(15,23,42,.045)}.members-card{padding:16px}.panel-head{padding:4px 4px 12px}.panel-head h2{margin:0 0 5px;font-size:16px}.panel-head p{margin:0;color:#7b8791;font-size:11px}.member-list{display:grid;gap:8px}.member-row{width:100%;display:flex;align-items:center;gap:10px;padding:11px;border:1px solid transparent;border-radius:13px;background:#fbfcfd;text-align:left;cursor:pointer;transition:.15s}.member-row:hover{border-color:#dbe7e9;background:#fff}.member-row.active{border-color:#a8dcd8;background:#eefaf9;box-shadow:inset 0 0 0 1px rgba(7,139,135,.08)}.avatar{width:36px;height:36px;border-radius:11px;display:grid;place-items:center;background:#e8f7f5;color:#078b87;font-size:11px;font-weight:950;flex:none}.avatar.large{width:46px;height:46px;border-radius:14px;font-size:13px}.member-copy{display:grid;gap:3px;min-width:0;flex:1}.member-copy strong{font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.member-copy small{font-size:10px;color:#73808a;text-transform:capitalize}.chevron{font-size:22px;color:#9aa5ad;line-height:1}.empty{display:grid;gap:4px;padding:22px 12px;text-align:center;color:#7b8791;font-size:11px}.empty strong{color:#35424c;font-size:12px}
.permissions-card{padding:18px;overflow:hidden}.selected-head{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:2px 2px 16px}.selected-person{display:flex;align-items:center;gap:12px;min-width:0}.selected-person h2{margin:4px 0 2px;font-size:18px}.selected-person p{margin:0;color:#74808a;font-size:11px}.save-btn{border:0;border-radius:11px;padding:11px 15px;background:#17202b;color:#fff;font-weight:900;font-size:11px;cursor:pointer;white-space:nowrap}.save-btn:disabled{opacity:.5;cursor:wait}.matrix-wrap{overflow:auto;border:1px solid #e3eaed;border-radius:14px}.matrix{width:100%;border-collapse:separate;border-spacing:0;min-width:760px}.matrix th{position:sticky;top:0;z-index:1;background:#f7fafb;color:#66737d;font-size:9px;text-transform:uppercase;letter-spacing:.08em;font-weight:950;padding:12px 10px;border-bottom:1px solid #dfe7ea;text-align:center;white-space:nowrap}.matrix th.module-col{text-align:left;width:280px}.matrix td{border-bottom:1px solid #edf1f3}.matrix tr:last-child td{border-bottom:0}.module-cell{padding:12px 13px}.module-cell strong{display:block;font-size:11px;color:#26333d}.module-cell span{display:block;margin-top:3px;font-size:9px;color:#8a959d}.check-cell{text-align:center;width:72px}.check{display:inline-grid;place-items:center;cursor:pointer;padding:7px}.check input{position:absolute;opacity:0;pointer-events:none}.check span{width:17px;height:17px;border:1.5px solid #c8d5d9;border-radius:5px;background:#fff;display:block;position:relative;transition:.15s}.check input:checked+span{background:#078b87;border-color:#078b87}.check input:checked+span:after{content:'';position:absolute;left:5px;top:1px;width:4px;height:8px;border:solid #fff;border-width:0 2px 2px 0;transform:rotate(45deg)}.check input:focus-visible+span{outline:3px solid rgba(7,139,135,.16);outline-offset:2px}.footer-note{display:flex;justify-content:space-between;gap:12px;margin-top:12px;padding:10px 12px;border-radius:11px;background:#f7f9fa;color:#76838d;font-size:10px}.footer-note strong{color:#42505a}
.empty-state{min-height:460px;display:grid;place-items:center;align-content:center;text-align:center;padding:40px}.empty-icon{width:48px;height:48px;border-radius:15px;display:grid;place-items:center;background:#eefaf9;color:#078b87;font-size:20px;font-weight:950;margin-bottom:8px}.empty-state h2{margin:0 0 5px;font-size:18px}.empty-state p{margin:0;color:#7b8791;font-size:12px;max-width:310px;line-height:1.6}
@media(max-width:920px){.access-grid{grid-template-columns:1fr}.members-card{padding-bottom:12px}.member-list{grid-template-columns:repeat(2,minmax(0,1fr))}.hero{align-items:flex-start}.hero-note{text-align:left}}@media(max-width:640px){.hero{display:grid}.hero h1{font-size:27px}.hero-note{width:max-content}.member-list{grid-template-columns:1fr}.permissions-card{padding:12px}.selected-head{align-items:flex-start;flex-direction:column}.save-btn{width:100%}.footer-note{display:grid}.matrix th,.matrix td{padding-left:8px;padding-right:8px}}
`;
