'use client';

import { useEffect, useMemo, useState } from 'react';
import AppShell from '../../components/AppShell';
import { getSupabase } from '../../../../lib/supabase-browser';

type Member={id:string;user_id:string;employee_id:string;role:string;active:boolean;profiles?:{full_name?:string}|null};
type Permission={id?:string;user_id:string;workspace_id?:string;module:string;can_view:boolean;can_create:boolean;can_edit:boolean;can_submit:boolean;can_approve:boolean;can_publish:boolean;can_manage:boolean};
type Access={role:string;is_owner_or_admin:boolean};

const modules=[
 ['dashboard','Dashboard'],['content','Content / Create Post'],['creative','Creative Intelligence'],['drafts','Drafts'],['calendar','Calendar'],['approval','Approvals'],['publishing','Publishing History'],['analytics','Analytics'],['social_accounts','Social Accounts'],['team','Team Management']
] as const;
const actions=['can_view','can_create','can_edit','can_submit','can_approve','can_publish','can_manage'] as const;
const actionLabels:Record<string,string>={can_view:'View',can_create:'Create',can_edit:'Edit',can_submit:'Submit',can_approve:'Approve',can_publish:'Publish',can_manage:'Manage'};
const blankPermissions=(userId:string,module:string):Permission=>({user_id:userId,module,can_view:false,can_create:false,can_edit:false,can_submit:false,can_approve:false,can_publish:false,can_manage:false});

export default function EmployeeAccessPage(){
 const[id,setId]=useState(''),[members,setMembers]=useState<Member[]>([]),[selected,setSelected]=useState(''),[access,setAccess]=useState<Access|null>(null),[permissions,setPermissions]=useState<Record<string,Permission>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[removeOpen,setRemoveOpen]=useState(false),[removing,setRemoving]=useState(false);
 const selectedMember=useMemo(()=>members.find(m=>m.user_id===selected)||null,[members,selected]);
 const assignedAccess=useMemo(()=>{const out:{module:string;label:string;actions:string[]}[]=[];for(const [module,label] of modules){const p=permissions[module];if(!p)continue;const enabled=actions.filter(a=>p[a]).map(a=>actionLabels[a]);if(enabled.length)out.push({module,label,actions:enabled});}return out},[permissions]);
 async function token(){const s=(await getSupabase().auth.getSession()).data.session;if(!s)throw new Error('Session expired');return s.access_token}
 async function load(){
  setLoading(true);setMessage('');
  try{
   const saved=localStorage.getItem('mdsm:selectedWorkspaceId')||''; if(!saved){location.href='/dashboard';return}
   setId(saved);const t=await token();
   const accessRes=await fetch(`/api/workspace-access?workspace_id=${encodeURIComponent(saved)}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const ad=await accessRes.json();
   if(!accessRes.ok||!ad.is_owner_or_admin){location.href='/dashboard';return} setAccess(ad);
   const mRes=await fetch(`/api/workspace-employees?workspace_id=${encodeURIComponent(saved)}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const md=await mRes.json();
   if(!mRes.ok)throw new Error(md?.error||'Unable to load employees.');setMembers(md.members||[]);
  }catch(e){setMessage(e instanceof Error?e.message:'Unable to load employee access.');}finally{setLoading(false)}
 }
 async function loadPermissions(userId:string){
  setSelected(userId);setMessage('');
  try{const t=await token();const r=await fetch(`/api/admin/permissions?workspace_id=${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Unable to load permissions.');const next:Record<string,Permission>={};(d.permissions||[]).filter((p:Permission)=>p.user_id===userId).forEach((p:Permission)=>{next[p.module]=p});setPermissions(next)}catch(e){setMessage(e instanceof Error?e.message:'Unable to load permissions.')}}
 function toggle(module:string,action:string){setPermissions(cur=>{const base=cur[module]||blankPermissions(selected,module);return {...cur,[module]:{...base,[action]:!base[action as keyof Permission]}}})}
 async function saveAll(){if(!selectedMember)return;setSaving(true);setMessage('');try{const t=await token();for(const [module,label] of modules){const p=permissions[module]||blankPermissions(selectedMember.user_id,module);const permissionPayload={module,can_view:p.can_view,can_create:p.can_create,can_edit:p.can_edit,can_submit:p.can_submit,can_approve:p.can_approve,can_publish:p.can_publish,can_manage:p.can_manage};const r=await fetch('/api/admin/permissions',{method:'PUT',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({workspace_id:id,user_id:selectedMember.user_id,...permissionPayload})});const d=await r.json();if(!r.ok)throw new Error(d?.error||`Unable to save ${label}.`)}setMessage('Employee access saved successfully.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save employee access')}finally{setSaving(false)}}
 async function setActive(active:boolean){if(!selectedMember)return;setMessage('');try{const t=await token();const r=await fetch('/api/admin/memberships',{method:'PATCH',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({workspace_id:id,member_id:selectedMember.id,active})});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Unable to update employee.');setMembers(cur=>cur.map(m=>m.id===selectedMember.id?{...m,...d.membership}:m));setMessage(active?'Employee activated.':'Employee deactivated.');if(!active){setSelected('');setPermissions({})}}catch(e){setMessage(e instanceof Error?e.message:'Unable to update employee.')}}
 async function removeEmployee(){if(!selectedMember)return;setRemoving(true);setMessage('');try{const t=await token();const r=await fetch('/api/admin/memberships',{method:'DELETE',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({workspace_id:id,member_id:selectedMember.id})});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Unable to remove employee.');setMembers(cur=>cur.filter(m=>m.id!==selectedMember.id));setSelected('');setPermissions({});setRemoveOpen(false);setMessage(`${selectedMember.employee_id} removed from this workspace.`)}catch(e){setMessage(e instanceof Error?e.message:'Unable to remove employee.')}finally{setRemoving(false)}}
 useEffect(()=>{void load()},[]);
 if(loading)return <AppShell title="Settings"><style jsx>{styles}</style><div className="access-loading"><div className="spinner"/><span>Loading employee access…</span></div></AppShell>;
 return <AppShell title="Settings"><style jsx>{styles}</style>
  <div className="access-page">
   <header className="hero"><div><span className="eyebrow">TEAM ACCESS</span><h1>Employee Access</h1><p>Set precise module permissions for each active team member. Changes apply only to the selected workspace.</p></div><div className="hero-note"><strong>{members.filter(m=>m.role!=='owner'&&m.active).length}</strong><span>active team members</span></div></header>
   {message&&<div className="notice" role="status"><span className="notice-dot"/>{message}</div>}
   <div className="access-grid">
    <aside className="members-card panel"><div className="panel-head"><div><h2>Team Members</h2><p>Select a member to edit access.</p></div></div><div className="member-list">{members.filter(m=>m.role!=='owner'&&m.active).map(m=><button key={m.user_id} className={`member-row ${selected===m.user_id?'active':''}`} onClick={()=>void loadPermissions(m.user_id)}><span className="avatar">{(m.profiles?.full_name||m.employee_id).slice(0,2).toUpperCase()}</span><span className="member-copy"><strong>{m.profiles?.full_name||m.employee_id}</strong><small>{m.employee_id} · {m.role}</small></span><span className="chevron">›</span></button>)}{members.filter(m=>m.role!=='owner'&&m.active).length===0&&<div className="empty"><strong>No active employees</strong><span>Create or activate a team member first.</span></div>}</div></aside>
    <section className="permissions-card panel">{!selectedMember?<div className="empty-state"><div className="empty-icon">✓</div><h2>Select an employee</h2><p>Choose a team member from the left to configure their permissions.</p></div>:<>
      <div className="selected-head"><div className="selected-person"><div className="avatar large">{(selectedMember.profiles?.full_name||selectedMember.employee_id).slice(0,2).toUpperCase()}</div><div><span className="eyebrow">SELECTED MEMBER</span><h2>{selectedMember.profiles?.full_name||selectedMember.employee_id}</h2><p>{selectedMember.employee_id} · {selectedMember.role}</p></div></div><div className="head-actions"><button className="secondary-btn" onClick={()=>void setActive(false)}>Deactivate</button><button className="danger-btn" onClick={()=>setRemoveOpen(true)}>Remove Employee</button><button className="save-btn" onClick={()=>void saveAll()} disabled={saving}>{saving?'Saving…':'Save Access'}</button></div></div>
      <div className="summary-card"><div className="summary-title"><strong>Current Access</strong><span>{assignedAccess.length} module{assignedAccess.length===1?'':'s'} enabled</span></div>{assignedAccess.length?<div className="summary-list">{assignedAccess.map(item=><div key={item.module} className="summary-row"><strong>{item.label}</strong><div>{item.actions.map(a=><span key={a} className="access-chip">{a}</span>)}</div></div>)}</div>:<div className="summary-empty">No module permissions assigned yet.</div>}</div>
      <div className="matrix-wrap"><table className="matrix"><thead><tr><th className="module-col">Module</th>{actions.map(a=><th key={a}>{actionLabels[a]}</th>)}</tr></thead><tbody>{modules.map(([module,label])=><tr key={module}><td className="module-cell"><strong>{label}</strong><span>{module==='content'?'Posts and content creation':module==='social_accounts'?'Connected social channels':'Workspace module'}</span></td>{actions.map(a=><td key={a} className="check-cell"><label className="check"><input type="checkbox" checked={Boolean(permissions[module]?.[a])} onChange={()=>toggle(module,a)} aria-label={`${label} ${actionLabels[a]}`}/><span/></label></td>)}</tr>)}</tbody></table></div>
      <div className="footer-note"><span>Workspace Settings is not assignable here.</span><strong>Owner / Admin only</strong></div>
    </>}</section>
   </div>
  </div>
  {removeOpen&&selectedMember&&<div className="modal-backdrop"><div className="confirm-modal"><div className="confirm-icon">!</div><span className="eyebrow">REMOVE EMPLOYEE</span><h2>Remove {selectedMember.employee_id}?</h2><p>This will remove the employee from this workspace. Their current role and permissions are shown below before you confirm.</p><div className="confirm-meta"><span><small>Name</small><strong>{selectedMember.profiles?.full_name||selectedMember.employee_id}</strong></span><span><small>Role</small><strong>{selectedMember.role}</strong></span></div><div className="confirm-access">{assignedAccess.length?assignedAccess.map(item=><div key={item.module}><strong>{item.label}</strong><span>{item.actions.join(' · ')}</span></div>):<span>No module permissions assigned.</span>}</div><div className="modal-actions"><button className="cancel-btn" onClick={()=>setRemoveOpen(false)} disabled={removing}>Cancel</button><button className="danger-confirm" onClick={()=>void removeEmployee()} disabled={removing}>{removing?'Removing…':'Remove Employee'}</button></div></div></div>}
 </AppShell>;
}

const styles=`
.access-page{min-height:100%;padding-bottom:28px}.access-loading{min-height:320px;display:grid;place-items:center;gap:10px;color:#66727d;font-size:13px}.spinner{width:24px;height:24px;border:3px solid #dbe7e9;border-top-color:#078b87;border-radius:50%;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
.hero{display:flex;justify-content:space-between;gap:24px;align-items:flex-end;margin-bottom:22px}.hero h1{margin:6px 0 8px;font-size:32px;letter-spacing:-.035em}.hero p{margin:0;color:#6f7c87;max-width:720px;line-height:1.6;font-size:13px}.hero-note{display:grid;gap:2px;text-align:right;padding:12px 16px;border:1px solid #dfe8ea;background:#fff;border-radius:14px;min-width:120px}.hero-note strong{font-size:22px;color:#17202b}.hero-note span{font-size:10px;color:#73808b;font-weight:800;text-transform:uppercase;letter-spacing:.08em}
.eyebrow{font-size:10px;letter-spacing:.12em;color:#078b87;font-weight:950}.notice{display:flex;align-items:center;gap:9px;margin:0 0 16px;padding:11px 13px;border:1px solid #d7ebe8;background:#f3fbfa;color:#1e5e59;border-radius:12px;font-size:12px;font-weight:750}.notice-dot{width:7px;height:7px;border-radius:50%;background:#078b87;flex:none}.access-grid{display:grid;grid-template-columns:290px minmax(0,1fr);gap:18px;align-items:start}.panel{background:#fff;border:1px solid #e1eaed;border-radius:18px;box-shadow:0 10px 30px rgba(15,23,42,.045)}.members-card{padding:16px}.panel-head{padding:4px 4px 12px}.panel-head h2{margin:0 0 5px;font-size:16px}.panel-head p{margin:0;color:#7b8791;font-size:11px}.member-list{display:grid;gap:8px}.member-row{width:100%;display:flex;align-items:center;gap:10px;padding:11px;border:1px solid transparent;border-radius:13px;background:#fbfcfd;text-align:left;cursor:pointer;transition:.15s}.member-row:hover{border-color:#dbe7e9;background:#fff}.member-row.active{border-color:#a8dcd8;background:#eefaf9;box-shadow:inset 0 0 0 1px rgba(7,139,135,.08)}.avatar{width:36px;height:36px;border-radius:11px;display:grid;place-items:center;background:#e8f7f5;color:#078b87;font-size:11px;font-weight:950;flex:none}.avatar.large{width:46px;height:46px;border-radius:14px;font-size:13px}.member-copy{display:grid;gap:3px;min-width:0;flex:1}.member-copy strong{font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.member-copy small{font-size:10px;color:#73808a;text-transform:capitalize}.chevron{font-size:22px;color:#9aa5ad;line-height:1}.empty{display:grid;gap:4px;padding:22px 12px;text-align:center;color:#7b8791;font-size:11px}.empty strong{color:#35424c;font-size:12px}
.permissions-card{padding:18px;overflow:hidden}.selected-head{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:2px 2px 14px}.selected-person{display:flex;align-items:center;gap:12px;min-width:0}.selected-person h2{margin:4px 0 2px;font-size:18px}.selected-person p{margin:0;color:#74808a;font-size:11px}.head-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap;justify-content:flex-end}.save-btn,.secondary-btn,.danger-btn{border-radius:10px;padding:10px 12px;font-weight:900;font-size:10px;cursor:pointer;white-space:nowrap}.save-btn{border:0;background:#17202b;color:#fff}.secondary-btn{border:1px solid #dce5e8;background:#fff;color:#35424c}.danger-btn{border:1px solid #f2c9c5;background:#fff7f6;color:#b42318}.save-btn:disabled,.secondary-btn:disabled,.danger-btn:disabled{opacity:.5;cursor:wait}
.summary-card{margin-bottom:14px;border:1px solid #e3eaed;border-radius:14px;background:#fafcfc;padding:13px}.summary-title{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:10px;font-size:11px}.summary-title span{font-size:9px;color:#7a8790;text-transform:uppercase;letter-spacing:.08em}.summary-list{display:grid;gap:7px}.summary-row{display:grid;grid-template-columns:190px 1fr;gap:10px;align-items:center}.summary-row strong{font-size:10px;color:#43505a}.summary-row>div{display:flex;flex-wrap:wrap;gap:5px}.access-chip{display:inline-flex;align-items:center;padding:4px 7px;border-radius:999px;background:#e8f7f5;color:#087f7b;font-size:9px;font-weight:900}.summary-empty{font-size:10px;color:#7d8992}
.matrix-wrap{overflow:auto;border:1px solid #e3eaed;border-radius:14px}.matrix{width:100%;border-collapse:separate;border-spacing:0;min-width:760px}.matrix th{position:sticky;top:0;z-index:1;background:#f7fafb;color:#66737d;font-size:9px;text-transform:uppercase;letter-spacing:.08em;font-weight:950;padding:12px 10px;border-bottom:1px solid #dfe7ea;text-align:center;white-space:nowrap}.matrix th.module-col{text-align:left;width:280px}.matrix td{border-bottom:1px solid #edf1f3}.matrix tr:last-child td{border-bottom:0}.module-cell{padding:12px 13px}.module-cell strong{display:block;font-size:11px;color:#26333d}.module-cell span{display:block;margin-top:3px;font-size:9px;color:#8a959d}.check-cell{text-align:center;width:72px}.check{display:inline-grid;place-items:center;cursor:pointer;padding:7px}.check input{position:absolute;opacity:0;pointer-events:none}.check span{width:17px;height:17px;border:1.5px solid #c8d5d9;border-radius:5px;background:#fff;display:block;position:relative;transition:.15s}.check input:checked+span{background:#078b87;border-color:#078b87}.check input:checked+span:after{content:'';position:absolute;left:5px;top:1px;width:4px;height:8px;border:solid #fff;border-width:0 2px 2px 0;transform:rotate(45deg)}.check input:focus-visible+span{outline:3px solid rgba(7,139,135,.16);outline-offset:2px}.footer-note{display:flex;justify-content:space-between;gap:12px;margin-top:12px;padding:10px 12px;border-radius:11px;background:#f7f9fa;color:#76838d;font-size:10px}.footer-note strong{color:#42505a}
.empty-state{min-height:520px;display:grid;place-items:center;align-content:center;text-align:center;padding:40px}.empty-icon{width:48px;height:48px;border-radius:15px;display:grid;place-items:center;background:#eefaf9;color:#078b87;font-size:20px;font-weight:950;margin-bottom:8px}.empty-state h2{margin:0 0 5px;font-size:18px}.empty-state p{margin:0;color:#7b8791;font-size:12px;max-width:310px;line-height:1.6}
.modal-backdrop{position:fixed;inset:0;background:rgba(15,23,42,.5);display:grid;place-items:center;padding:18px;z-index:100}.confirm-modal{width:min(560px,100%);max-height:min(86vh,760px);overflow:auto;background:#fff;border-radius:20px;border:1px solid #e0e8ea;box-shadow:0 28px 90px rgba(15,23,42,.25);padding:22px}.confirm-icon{width:38px;height:38px;border-radius:12px;background:#fff2f0;color:#b42318;display:grid;place-items:center;font-weight:950;margin-bottom:12px}.confirm-modal h2{margin:6px 0 8px;font-size:21px}.confirm-modal p{margin:0 0 16px;color:#697680;font-size:12px;line-height:1.6}.confirm-meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:13px}.confirm-meta span{display:grid;gap:3px;padding:10px 11px;border:1px solid #e6ecee;border-radius:11px;background:#fafcfc}.confirm-meta small{font-size:9px;text-transform:uppercase;letter-spacing:.08em;color:#7d8992;font-weight:900}.confirm-meta strong{font-size:11px;color:#26333d}.confirm-access{display:grid;gap:7px;padding:12px;border:1px solid #e5ebed;border-radius:12px;background:#f9fbfb;margin-bottom:18px}.confirm-access>div{display:grid;grid-template-columns:170px 1fr;gap:8px;font-size:10px}.confirm-access strong{color:#3b4650}.confirm-access span{color:#6c7983}.modal-actions{display:flex;justify-content:flex-end;gap:9px}.cancel-btn,.danger-confirm{height:42px;padding:0 14px;border-radius:10px;font-weight:900;font-size:11px;cursor:pointer}.cancel-btn{border:1px solid #dce5e8;background:#fff;color:#36434d}.danger-confirm{border:0;background:#b42318;color:#fff}.cancel-btn:disabled,.danger-confirm:disabled{opacity:.5;cursor:wait}
@media(max-width:1050px){.access-grid{grid-template-columns:1fr}.members-card{padding-bottom:12px}.member-list{grid-template-columns:repeat(2,minmax(0,1fr))}.hero{align-items:flex-start}.hero-note{text-align:left}}@media(max-width:700px){.hero{display:grid}.hero h1{font-size:27px}.hero-note{width:max-content}.member-list{grid-template-columns:1fr}.permissions-card{padding:12px}.selected-head{align-items:flex-start;flex-direction:column}.head-actions{width:100%;justify-content:stretch}.head-actions>*{flex:1}.summary-row{grid-template-columns:1fr}.footer-note{display:grid}.matrix th,.matrix td{padding-left:8px;padding-right:8px}.confirm-meta{grid-template-columns:1fr}.confirm-access>div{grid-template-columns:1fr;gap:2px}.modal-actions{display:grid;grid-template-columns:1fr 1fr}.cancel-btn,.danger-confirm{width:100%}}
`;
