'use client';
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

export default function LeadCapturePage(){
 const[workspaceId,setWorkspaceId]=useState(''),[exists,setExists]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function check(id:string){try{const r=await getSupabase().from('feedback_forms').select('id,name').eq('workspace_id',id).ilike('name','%Lead Capture%').limit(1).maybeSingle();if(r.error)throw r.error;setExists(Boolean(r.data))}catch(e){setError(e instanceof Error?e.message:'Unable to check lead form.')}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);if(id)void check(id)},[]);
 async function create(){setBusy(true);setError('');setMessage('');try{if(!workspaceId)throw Error('Select a workspace first.');const sb=getSupabase(),s=(await sb.auth.getSession()).data.session;if(!s)throw Error('Session expired.');const a=await fetch('/api/workspace-access?workspace_id='+encodeURIComponent(workspaceId),{headers:{Authorization:'Bearer '+s.access_token},cache:'no-store'});const ad=await a.json();if(!a.ok||(!ad?.is_owner_or_admin&&!['owner','admin','manager'].includes(String(ad?.effectiveRole||'').toLowerCase())))throw Error('Only a workspace manager can create the lead form.');const now=new Date().toISOString();const payload={workspace_id:workspaceId,name:'Lead Capture',slug:'lead-capture',title:'Tell us what you need',description:'Share your contact details and what you are looking for. Our team will follow up.',fields:[{id:crypto.randomUUID(),label:'Full name',type:'text',required:true},{id:crypto.randomUUID(),label:'Email',type:'text',required:true},{id:crypto.randomUUID(),label:'Phone',type:'text',required:false},{id:crypto.randomUUID(),label:'What do you need?',type:'textarea',required:false}],active:true,ai_enabled:false,created_at:now,updated_at:now};const r=await sb.from('feedback_forms').insert(payload);if(r.error)throw r.error;setExists(true);setMessage('Lead Capture form created.')}catch(e){setError(e instanceof Error?e.message:'Unable to create lead form.')}finally{setBusy(false)}}
 return <AppShell title='Lead Capture Form'><style jsx>{".page{display:grid;gap:14px}.panel{padding:18px}.hero h1{margin:5px 0}.note{font-size:10px;color:#667085;line-height:1.6}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{border:1px solid #dbe4e8;background:#fff;border-radius:9px;padding:9px 11px;font-size:9px;font-weight:900;cursor:pointer}.primary{background:#087f7b;color:#fff;border-color:#087f7b}"} </style><div className='page'><section className='panel hero'><div className='eyebrow'>LEAD CAPTURE</div><h1>Lead Capture Form</h1><p className='note'>Create a ready-to-use form preset for name, email, phone and enquiry details. Submissions appear in Feedback Responses.</p></section>{error&&<div className='alert alert-error'>{error}</div>}{message&&<div className='alert alert-success'>{message}</div>}<section className='panel'><h2 style={{margin:'0 0 5px'}}>Workspace lead form</h2><p className='note'>{exists?'A Lead Capture form already exists.':'Create the preset, then customize it from Feedback Forms.'}</p><div className='actions' style={{marginTop:10}}><button className='btn primary' disabled={busy||exists} onClick={()=>void create()}>{exists?'Already Created':busy?'Creating…':'Create Lead Capture Form'}</button><button className='btn' onClick={()=>location.href='/dashboard/gmb/forms'}>Manage Forms →</button><button className='btn' onClick={()=>location.href='/dashboard/gmb/responses'}>View Leads →</button></div></section></div></AppShell>
}
