'use client';
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

export default function RatingImprovementPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[data,setData]=useState<any>(null),[busy,setBusy]=useState(true),[error,setError]=useState('');
 async function load(id:string){setBusy(true);setError('');try{const s=(await getSupabase().auth.getSession()).data.session;if(!s){location.href='/login';return}const r=await fetch('/api/google/business/rating-improvement?workspaceId='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+s.access_token},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to calculate suggestions.');setData(d)}catch(e){setError(e instanceof Error?e.message:'Unable to calculate suggestions.')}finally{setBusy(false)}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);if(id)void load(id)},[]);
 return <AppShell title='Rating Improvement Suggestions'><style jsx>{".page{display:grid;gap:14px}.panel{padding:18px}.hero h1{margin:5px 0}.note{font-size:10px;color:#667085;line-height:1.6}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{border:1px solid #dbe4e8;background:#fff;border-radius:9px;padding:9px 11px;font-size:9px;font-weight:900;cursor:pointer}.primary{background:#087f7b;color:#fff;border-color:#087f7b}.box{padding:12px;background:#f8fafb;border:1px solid #e7ecef;border-radius:10px;font-size:10px;line-height:1.55}.cards{display:grid;gap:9px}"} </style><div className='page'><section className='panel hero'><div className='eyebrow'>RATING IMPROVEMENT</div><h1>Rating Improvement Suggestions</h1><p className='note'>Recommendations are based on imported review patterns and never instruct the system to create or suppress reviews.</p></section>{error&&<div className='alert alert-error'>{error}</div>}<section className='panel'><div className='eyebrow'>CURRENT RATING</div><h2 style={{margin:'5px 0'}}>{busy?'Calculating…':data?.averageRating==null?'—':data.averageRating.toFixed(2)+'/5'}</h2><p className='note'>Model: {data?.model||'—'}</p></section><section className='panel'><div className='eyebrow'>ACTIONS</div><div className='cards'>{(data?.suggestions||[]).map((x:string,i:number)=><div className='box' key={i}>{i+1}. {x}</div>)}</div><div className='actions' style={{marginTop:11}}><button className='btn primary' disabled={busy||!workspaceId} onClick={()=>void load(workspaceId)}>Refresh Suggestions</button><button className='btn' onClick={()=>location.href='/dashboard/gmb/ai'}>Reputation AI →</button></div></section></div></AppShell>
}
