'use client';

import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

type Conversation={id:string;phone:string;contact_name:string|null;service_window_open:boolean};
const css=`
.page{display:grid;gap:14px}.head{display:flex;justify-content:space-between;gap:15px;align-items:flex-end;flex-wrap:wrap}.head h1{margin:5px 0}.head p{margin:0;color:#73818b;font-size:10px}.grid{display:grid;grid-template-columns:330px 1fr;gap:14px}.panel{padding:17px}.list{display:grid;gap:5px;margin-top:11px}.conv{border:1px solid #e1e8eb;background:#fff;border-radius:10px;padding:10px;text-align:left;cursor:pointer}.conv.active{border-color:#087f7b;background:#edf9f7}.conv strong{display:block;font-size:10px}.conv small{display:block;color:#819099;font-size:8px;margin-top:3px}.form{display:grid;gap:10px}.label{display:grid;gap:5px;font-size:9px;font-weight:900}.input{width:100%;box-sizing:border-box;padding:10px;border:1px solid #dce5e9;border-radius:9px;font-size:10px}.button-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.btn{border:1px solid #dce5e9;background:#fff;border-radius:9px;padding:9px 11px;font-size:9px;font-weight:900;cursor:pointer}.primary{background:#087f7b;color:#fff;border-color:#087f7b}.notice{padding:10px 12px;background:#fff;border:1px solid #dce5e9;border-radius:9px;font-size:10px}.error{padding:10px 12px;background:#fff1f2;border:1px solid #f5c8cf;color:#9f1239;border-radius:9px;font-size:10px}.muted{color:#7d8992;font-size:9px}.empty{padding:35px 10px;text-align:center;color:#7d8992;font-size:10px}@media(max-width:850px){.grid{grid-template-columns:1fr}}
`;
export default function WhatsAppButtonsPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[conversations,setConversations]=useState<Conversation[]>([]),[selectedId,setSelectedId]=useState(''),[text,setText]=useState(''),[header,setHeader]=useState(''),[footer,setFooter]=useState(''),[buttons,setButtons]=useState([{id:'yes',title:'Yes'},{id:'no',title:'No'},{id:'help',title:'Need Help'}]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function token(){const s=(await getSupabase().auth.getSession()).data.session;if(!s)throw new Error('Session expired');return s.access_token}
 async function load(id:string){if(!id)return;setLoading(true);try{const t=await token();const r=await fetch('/api/whatsapp/conversations?workspaceId='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+t},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to load conversations.');setConversations(d.conversations||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load conversations.')}finally{setLoading(false)}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);if(id)void load(id);else setLoading(false);const onWorkspace=(e:Event)=>{const next=(e as CustomEvent<{workspaceId?:string}>).detail?.workspaceId||'';if(next&&next!==id){id=next;setWorkspaceId(next);void load(next)}};window.addEventListener('mdsm:workspace-changed',onWorkspace);return()=>window.removeEventListener('mdsm:workspace-changed',onWorkspace)},[]);
 function updateButton(i:number,key:'id'|'title',value:string){setButtons(cur=>cur.map((b,n)=>n===i?{...b,[key]:value}:b))}
 async function send(){setSaving(true);setNotice('');setError('');try{const selected=conversations.find(c=>c.id===selectedId);if(!selected)throw Error('Select a conversation.');if(!selected.service_window_open)throw Error('The 24-hour window is closed. Use an approved template.');const t=await token();const r=await fetch('/api/whatsapp/interactive',{method:'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,conversationId:selectedId,headerText:header,text,footer,buttons:buttons.filter(b=>b.title.trim())})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to send buttons.');setNotice('Button message sent.');setText('')}catch(e){setError(e instanceof Error?e.message:'Unable to send buttons.')}finally{setSaving(false)}}
 return <AppShell title='WhatsApp Buttons'><style jsx>{css}</style><div className='page'><div className='head'><div><div className='eyebrow'>WHATSAPP • BUTTON CONVERSATIONS</div><h1>Button-Based Conversations</h1><p>Send up to three reply buttons inside the active customer service window.</p></div><button className='btn' onClick={()=>void load(workspaceId)}>↻ Refresh</button></div>{notice&&<div className='notice'>{notice}</div>}{error&&<div className='error'>{error}</div>}<div className='grid'><section className='panel'><div className='eyebrow'>CONVERSATIONS</div><div className='list'>{loading?<div className='empty'>Loading…</div>:conversations.length?conversations.map(c=><button className={'conv '+(c.id===selectedId?'active':'')} key={c.id} onClick={()=>setSelectedId(c.id)}><strong>{c.contact_name||c.phone}</strong><small>{c.phone} · {c.service_window_open?'24h window open':'Template required'}</small></button>):<div className='empty'>No conversations.</div>}</div></section><section className='panel'><div className='eyebrow'>INTERACTIVE MESSAGE</div><h2 style={{margin:'6px 0'}}>Create Reply Buttons</h2><p className='muted'>Use clear actions such as “Yes”, “No”, “Get Price”, or “Book Now”.</p><div className='form' style={{marginTop:13}}><label className='label'>Header<input className='input' value={header} onChange={e=>setHeader(e.target.value)} placeholder='Optional header'/></label><label className='label'>Message<input className='input' value={text} onChange={e=>setText(e.target.value)} placeholder='Choose an option below'/></label>{buttons.map((b,i)=><div className='button-row' key={i}><input className='input' value={b.id} onChange={e=>updateButton(i,'id',e.target.value)} placeholder='button id'/><input className='input' value={b.title} onChange={e=>updateButton(i,'title',e.target.value)} placeholder='Button title'/></div>)}<label className='label'>Footer<input className='input' value={footer} onChange={e=>setFooter(e.target.value)} placeholder='Optional footer'/></label><button className='btn primary' disabled={saving||!selectedId||!text.trim()} onClick={()=>void send()}>{saving?'Sending…':'Send Button Message'}</button></div></section></div></div></AppShell>
}