import {NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';

async function client(request:Request){const token=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token)throw new Error('Authentication required.');const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new Error('Supabase configuration is missing.');const supabase=createClient(url,key,{global:{headers:{Authorization:`Bearer ${token}`}}});const {data,error}=await supabase.auth.getUser(token);if(error||!data.user)throw new Error('Invalid session.');return {supabase,userId:data.user.id}}

export async function GET(request:Request){try{const {supabase,userId}=await client(request),url=new URL(request.url),brandId=url.searchParams.get('brandId');let q=supabase.from('post_drafts').select('*').eq('user_id',userId).order('updated_at',{ascending:false});if(brandId)q=q.eq('brand_id',brandId);const {data,error}=await q;if(error)throw error;return NextResponse.json({drafts:data||[]})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to load drafts.'},{status:400})}}

export async function POST(request:Request){try{const {supabase,userId}=await client(request),body=await request.json();if(!body?.brand_id)throw new Error('Workspace is required.');const payload={user_id:userId,brand_id:body.brand_id,title:body.title||null,message:body.message||'',media_urls:Array.isArray(body.media_urls)?body.media_urls:[],platforms:Array.isArray(body.platforms)?body.platforms:[],status:body.status||'draft',scheduled_at:body.scheduled_at||null};const {data,error}=await supabase.from('post_drafts').insert(payload).select('*').single();if(error)throw error;return NextResponse.json({draft:data},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to create draft.'},{status:400})}}

export async function PATCH(request:Request){try{const {supabase,userId}=await client(request),body=await request.json();if(!body?.id)throw new Error('Draft id is required.');const allowed=['title','message','media_urls','platforms','status','scheduled_at','brand_id'];const patch:Object.fromEntries([] as never[])=Object.fromEntries(allowed.filter(k=>body[k]!==undefined).map(k=>[k,body[k]]));const {data,error}=await supabase.from('post_drafts').update({...patch,updated_at:new Date().toISOString()}).eq('id',body.id).eq('user_id',userId).select('*').single();if(error)throw error;return NextResponse.json({draft:data})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to update draft.'},{status:400})}}

export async function DELETE(request:Request){try{const {supabase,userId}=await client(request),body=await request.json();if(!body?.id)throw new Error('Draft id is required.');const {error}=await supabase.from('post_drafts').delete().eq('id',body.id).eq('user_id',userId);if(error)throw error;return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to delete draft.'},{status:400})}}
