import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

function db() { return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { autoRefreshToken:false, persistSession:false } }); }
async function user(req: NextRequest) { const token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,''); if(!token)return null; const c=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{global:{headers:{Authorization:`Bearer ${token}`}}}); const {data}=await c.auth.getUser(token); return data.user||null; }
function payload(body:any){ return { brand_id:String(body.brandId||''), account_ids:Array.isArray(body.accountIds)?body.accountIds:[], caption:String(body.caption||''), link:body.link||null, media_url:body.mediaUrl||null, scheduled_for:body.scheduledFor?new Date(body.scheduledFor).toISOString():new Date().toISOString(), status:'draft' }; }
export async function GET(req:NextRequest){const u=await user(req);if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});const p=new URL(req.url).searchParams;const brand=p.get('brandId');let q=db().from('scheduled_posts').select('*').eq('user_id',u.id).eq('status','draft').order('updated_at',{ascending:false});if(brand)q=q.eq('brand_id',brand);const {data,error}=await q;if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({drafts:data||[]});}
export async function POST(req:NextRequest){const u=await user(req);if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await req.json().catch(()=>null);const row=payload(b);if(!row.brand_id||!row.account_ids.length)return NextResponse.json({error:'brandId and at least one account are required.'},{status:400});const {data,error}=await db().from('scheduled_posts').insert({user_id:u.id,...row}).select('*').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({draft:data},{status:201});}
export async function PATCH(req:NextRequest){const u=await user(req);if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await req.json().catch(()=>null);if(!b?.id)return NextResponse.json({error:'id is required.'},{status:400});const row=payload(b);const {data,error}=await db().from('scheduled_posts').update(row).eq('id',b.id).eq('user_id',u.id).eq('status','draft').select('*').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({draft:data});}
export async function DELETE(req:NextRequest){const u=await user(req);if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'id is required.'},{status:400});const {error}=await db().from('scheduled_posts').delete().eq('id',id).eq('user_id',u.id).eq('status','draft');if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true});}
