import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const EMPLOYEE_DOMAIN = '@employee.md-hygiene.local';
function client(token:string){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new Error('Supabase configuration is missing.');return createClient(url,key,{global:{headers:{Authorization:`Bearer ${token}`}}})}
function adminClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY is missing in Vercel environment variables.');return createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}})}
async function auth(request:Request){const token=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token)return null;const sb=client(token);const {data,error}=await sb.auth.getUser(token);if(error||!data.user)return null;return{sb,user:data.user}}
async function admin(request:Request){const a=await auth(request);if(!a)return null;const {data:p}=await a.sb.from('profiles').select('role,active').eq('id',a.user.id).maybeSingle();return p?.role==='admin'&&p.active!==false?a:null}
export async function GET(request:Request){try{const a=await admin(request);if(!a)return NextResponse.json({error:'Admin access required.'},{status:403});const {data,error}=await a.sb.from('profiles').select('id,full_name,employee_id,role,active,created_at').order('created_at',{ascending:false});if(error)throw error;return NextResponse.json({staff:data||[]})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to load staff.'},{status:500})}}
export async function POST(request:Request){try{const a=await admin(request);if(!a)return NextResponse.json({error:'Admin access required.'},{status:403});const b=await request.json();const full_name=String(b.full_name||'').trim();const employee_id=String(b.employee_id||'').trim().toUpperCase();const password=String(b.password||'');const role=b.role==='admin'?'admin':'staff';const workplace_id=String(b.workplace_id||'').trim();if(!full_name||!employee_id||!password)return NextResponse.json({error:'Employee name, Employee ID and password are required.'},{status:400});if(password.length<6)return NextResponse.json({error:'Password must be at least 6 characters.'},{status:400});if(!/^[A-Z0-9._-]+$/.test(employee_id))return NextResponse.json({error:'Employee ID may contain only letters, numbers, dot, underscore or hyphen.'},{status:400});const sb=adminClient();const email=`${employee_id.toLowerCase()}${EMPLOYEE_DOMAIN}`;const {data:existing}=await sb.from('profiles').select('id').eq('employee_id',employee_id).maybeSingle();if(existing)return NextResponse.json({error:'Employee ID already exists.'},{status:409});const {data:created,error:createError}=await sb.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name,employee_id}});if(createError||!created.user)throw createError||new Error('Unable to create authentication user.');const userId=created.user.id;const {error:profileError}=await sb.from('profiles').update({full_name,employee_id,role,active:true}).eq('id',userId);if(profileError){await sb.auth.admin.deleteUser(userId);throw profileError}if(workplace_id){const {error:membershipError}=await sb.from('workplace_members').upsert({user_id:userId,workplace_id},{onConflict:'workplace_id,user_id'});if(membershipError){await sb.from('profiles').delete().eq('id',userId);await sb.auth.admin.deleteUser(userId);throw membershipError}}return NextResponse.json({staff:{id:userId,full_name,employee_id,role,active:true},message:'Employee created successfully.'},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to create employee.'},{status:400})}}
export async function PATCH(request:Request){try{const a=await admin(request);if(!a)return NextResponse.json({error:'Admin access required.'},{status:403});const b=await request.json();const id=String(b.id||'');if(!id)return NextResponse.json({error:'Staff id is required.'},{status:400});const updates:any={};if(typeof b.full_name==='string')updates.full_name=b.full_name.trim();if(typeof b.employee_id==='string')updates.employee_id=b.employee_id.trim().toUpperCase();if(typeof b.active==='boolean')updates.active=b.active;if(b.role==='admin'||b.role==='staff')updates.role=b.role;if(id===a.user.id&&updates.active===false)return NextResponse.json({error:'You cannot disable your own account.'},{status:400});const {data,error}=await a.sb.from('profiles').update(updates).eq('id',id).select('id,full_name,employee_id,role,active,created_at').single();if(error)throw error;return NextResponse.json({staff:data})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to update staff.'},{status:400})}}