'use client';
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

export default function ReviewStatusPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(id:string){setLoading(true);try{const s=(await getSupabase().auth.getSession()).data.session;if(!s){location.href='/login';return}const r=await fetch('/api/google/business/analytics?workspaceId='+encodeURIComponent(id)+'&days=90',{headers:{Authorization:'Bearer '+s.access_token},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to load review status.');setData(d)}catch(e){setError(e instanceof Error?e.message:'Unable to load review status.')}finally{setLoading(false)}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);if(id)void load(id)},[]);
 const m=data?.metrics;
 return <AppShell title='Review Status Dashboard'><style jsx>{".page{display:grid;gap:14px}.panel{padding:18px}.hero h1{margin:5px 0}.note{font-size:10px;color:#667085;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.metric span{display:block;font-size:9px;font-weight:900;color:#667085}.metric strong{display:block;font-size:24px;margin-top:5px}.row{display:flex;justify-content:space-between;gap:10px;padding:11px;border-top:1px solid #edf0f3;font-size:10px}.row:first-child{border-top:0}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:950px){.grid{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}}@media(max-width:600px){.grid{grid-template-columns:1fr}}"} </style><div className='page'><section className='panel'><div className='eyebrow'>REVIEW STATUS</div><h1>Review Status Dashboard</h1><p className='note'>90-day imported Google review status for the selected workspace.</p></section>{error&&<div className='alert alert-error'>{error}</div>}<div className='grid'>{[['Reviews',m?.reviews],['Replied',m?.replied],['Needs Reply',m?.needsReply],['Response Rate',m?m.responseRate+'%':'—'],['Average',m?.averageRating==null?'—':m.averageRating.toFixed(2)]].map(([t,v])=><article className='panel metric' key={String(t)}><span>{t}</span><strong>{loading?'—':v}</strong></article>)}</div><div className='two'><section className='panel'><div className='eyebrow'>RATING MIX</div><h2 style={{margin:'5px 0 10px'}}>Distribution</h2>{(data?.ratingDistribution||[]).slice().reverse().map((x:any)=><div className='row' key={x.rating}><span>{x.rating}★</span><strong>{x.count}</strong></div>)}</section><section className='panel'><div className='eyebrow'>LOCATIONS</div><h2 style={{margin:'5px 0 10px'}}>Location status</h2>{(data?.locations||[]).length?(data.locations||[]).map((x:any)=><div className='row' key={x.id}><span><strong>{x.business_name}</strong><br/><span className='note'>{x.reviews} reviews · avg {x.averageRating??'—'}</span></span><span>{x.needsReply} pending</span></div>):<p className='note'>No Business Profile locations imported.</p>}</section></div><section className='panel'><div className='eyebrow'>RECENT SIGNALS</div>{(data?.topRecentReviews||[]).length?(data.topRecentReviews||[]).map((x:any)=><div className='row' key={x.id}><span>{x.rating?('★'.repeat(x.rating)):'—'} · {x.business_name||'Business'}</span><span>{x.reply_status}</span></div>):<p className='note'>No recent reviews.</p>}</section></div></AppShell>
}
