'use client';
import { useEffect,useState } from 'react';
import AppShell from '../components/AppShell';
import { getSupabase } from '../../../lib/supabase-browser';

type Brand={id:string;name:string;slug:string}; type Account={id:string;platform:string;name:string;handle:string|null;brand_id:string|null};
export default function BrandsPage(){const[brands,setBrands]=useState<Brand[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[name,setName]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
async function load(){const s=(await getSupabase().auth.getSession()).data.session;if(!s){location.href='/login';return}const h={Authorization:`Bearer ${s.access_token}`};const [br,ac]=await Promise.all([fetch('/api/brands',{headers:h,cache:'no-store'}),getSupabase().from('social_accounts').select('id,platform,name,handle,brand_id').order('created_at',{ascending:false})]);const bd=await br.json();if(!br.ok)throw Error(bd.error||'Unable to load businesses');if(ac.error)throw ac.error;setBrands(bd.brands||[]);setAccounts((ac.data||[]) as Account[]);setLoading(false)}
useEffect(()=>{load().catch(e=>{setError(e.message);setLoading(false)})},[]);
async function createBrand(){if(!name.trim())return;setBusy(true);setError('');try{const s=(await getSupabase().auth.getSession()).data.session;const r=await fetch('/api/brands',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s?.access_token||''}`},body:JSON.stringify({name})});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to create business');setName('');setSuccess(`${d.brand.name} created.`);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create business')}finally{setBusy(false)}}
async function assign(accountId:string,brandId:string){const{error:e}=await getSupabase().from('social_accounts').update({brand_id:brandId||null}).eq('id',accountId);if(e)setError(e.message);else{setSuccess('Account assignment updated.');await load()}}
return <AppShell title="Businesses"><div className="page-head"><div><span className="eyebrow">WORKSPACES</span><h1>Businesses / Brands</h1><p>Create separate business cards and keep Facebook, Instagram and Google Business accounts isolated.</p></div><button className="btn btn-soft" onClick={()=>location.href='/dashboard'}>← Dashboard</button></div>{error&&<div className="alert alert-error">⚠ {error}</div>}{success&&<div className="alert alert-success">✓ {success}</div>}<section className="panel connect-panel"><div><span className="eyebrow">CREATE BUSINESS CARD</span><h2>New Business / Brand</h2><p>This becomes a separate dashboard workspace.</p></div><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. 24 Care"/><button className="btn btn-primary" disabled={busy||!name.trim()} onClick={createBrand}>{busy?'Creating…':'Create Card'}</button></section><section className="brand-card-grid">{loading?<div className="empty-state">Loading businesses…</div>:brands.map(b=><article className="panel" key={b.id}><div className="panel-head"><div><span className="eyebrow">BUSINESS</span><h2>{b.name}</h2></div><button className="btn btn-soft" onClick={()=>location.href=`/dashboard?brandId=${b.id}`}>Open Dashboard →</button></div><div className="account-list">{accounts.filter(a=>a.brand_id===b.id).map(a=><div className="account-row" key={a.id}><div className={`account-avatar ${a.platform}`}>{a.platform==='facebook'?'f':a.platform==='instagram'?'◎':'G'}</div><div className="account-info"><strong>{a.name}</strong><span>{a.handle?`@${a.handle}`:a.platform.replace('_',' ')}</span></div><span className="connected-pill">● Connected</span></div>)}{!accounts.some(a=>a.brand_id===b.id)&&<div className="empty-state">No accounts assigned yet.</div>}</div><label className="eyebrow">ASSIGN ACCOUNT</label><select defaultValue="" onChange={e=>e.target.value&&assign(e.target.value,b.id)}><option value="">Select an unassigned account…</option>{accounts.filter(a=>!a.brand_id).map(a=><option key={a.id} value={a.id}>{a.platform} — {a.name}</option>)}</select></article>)}</section></AppShell>}
