'use client';

import {useEffect,useMemo,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

type Conversation={id:string;phone:string;contact_name:string|null;service_window_open:boolean};
type Product={id:string;name:string;description:string|null;price:number;compare_at_price:number|null;featured:boolean;stock_quantity:number};
const css=`
.page{display:grid;gap:14px}.head{display:flex;justify-content:space-between;gap:15px;align-items:flex-end;flex-wrap:wrap}.head h1{margin:5px 0}.head p{margin:0;color:#73818b;font-size:10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.panel{padding:17px}.input{width:100%;box-sizing:border-box;padding:10px;border:1px solid #dce5e9;border-radius:9px;font-size:10px}.searchrow{display:flex;gap:7px;margin-top:11px}.btn{border:1px solid #dce5e9;background:#fff;border-radius:9px;padding:9px 11px;font-size:9px;font-weight:900;cursor:pointer}.primary{background:#17202b;color:#fff;border-color:#17202b}.cards{display:grid;gap:8px;margin-top:11px}.product{border:1px solid #e1e8eb;border-radius:11px;padding:11px;display:flex;justify-content:space-between;gap:12px;align-items:center}.product strong{font-size:10px}.product small{display:block;color:#849099;font-size:8px;line-height:1.45;margin-top:3px}.price{font-size:10px;font-weight:950}.pill{padding:5px 7px;border-radius:999px;background:#edf9f1;color:#087443;font-size:8px;font-weight:900}.list{display:grid;gap:6px;margin-top:11px}.conv{border:1px solid #e1e8eb;border-radius:9px;padding:9px;background:#fff;text-align:left;cursor:pointer}.conv.active{border-color:#087f7b;background:#edf9f7}.conv strong{display:block;font-size:9px}.conv small{color:#849099;font-size:8px}.notice{padding:10px 12px;background:#fff;border:1px solid #dce5e9;border-radius:9px;font-size:10px}.error{padding:10px 12px;background:#fff1f2;border:1px solid #f5c8cf;color:#9f1239;border-radius:9px;font-size:10px}.empty{padding:35px;text-align:center;color:#7d8992;font-size:10px}@media(max-width:850px){.grid{grid-template-columns:1fr}}
`;
export default function ProductSuggestionsPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[query,setQuery]=useState(''),[products,setProducts]=useState<Product[]>([]),[conversations,setConversations]=useState<Conversation[]>([]),[selectedId,setSelectedId]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function token(){const s=(await getSupabase().auth.getSession()).data.session;if(!s)throw new Error('Session expired');return s.access_token}
 async function load(id:string){if(!id)return;setLoading(true);try{const t=await token();const r=await fetch('/api/whatsapp/conversations?workspaceId='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+t},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to load conversations.');setConversations(d.conversations||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load conversations.')}finally{setLoading(false)}}
 async function suggest(){setError('');try{const t=await token();const r=await fetch('/api/catalog/suggestions?workspaceId='+encodeURIComponent(workspaceId)+'&q='+encodeURIComponent(query),{headers:{Authorization:'Bearer '+t},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to load suggestions.');setProducts(d.suggestions||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load suggestions.')}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);if(id){void Promise.all([load(id),suggest()])}else setLoading(false);const onWorkspace=(e:Event)=>{const next=(e as CustomEvent<{workspaceId?:string}>).detail?.workspaceId||'';if(next&&next!==id){id=next;setWorkspaceId(next);void load(next)}};window.addEventListener('mdsm:workspace-changed',onWorkspace);return()=>window.removeEventListener('mdsm:workspace-changed',onWorkspace)},[]);
 const selected=useMemo(()=>conversations.find(c=>c.id===selectedId),[conversations,selectedId]);
 async function send(p:Product){setBusy(true);setNotice('');setError('');try{if(!selected)throw Error('Select a conversation.');const suggestion='We recommend '+p.name+' for your requirement. Price: ₹'+Number(p.price||0).toFixed(2)+(p.compare_at_price!=null?' (offer price available).':'');const t=await token();const r=await fetch('/api/whatsapp/messages',{method:'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,conversationId:selected.id,text:suggestion})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to send suggestion.');setNotice('Product suggestion sent.')}catch(e){setError(e instanceof Error?e.message:'Unable to send suggestion.')}finally{setBusy(false)}}
 return <AppShell title='Product Suggestions'><style jsx>{css}</style><div className='page'><div className='head'><div><div className='eyebrow'>WHATSAPP • PRODUCT SUGGESTIONS</div><h1>Instant Product Suggestions</h1><p>Search the workspace catalogue and send a concise recommendation into an active WhatsApp conversation.</p></div></div>{notice&&<div className='notice'>{notice}</div>}{error&&<div className='error'>{error}</div>}<div className='grid'><section className='panel'><div className='eyebrow'>CATALOGUE</div><div className='searchrow'><input className='input' value={query} onChange={e=>setQuery(e.target.value)} placeholder='Search product, service or category…'/><button className='btn primary' onClick={()=>void suggest()}>Suggest</button></div><div className='cards'>{products.length?products.map(p=><article className='product' key={p.id}><div><strong>{p.name}</strong><small>{p.description||'Catalogue product'} · {p.stock_quantity>0?'In stock':'Out of stock'}</small></div><div style={{textAlign:'right'}}><div className='price'>₹{Number(p.price||0).toFixed(2)}</div><button className='btn' disabled={busy||p.stock_quantity<=0||!selected?.service_window_open} onClick={()=>void send(p)}>Send</button></div></article>):<div className='empty'>No matching products.</div>}</div></section><section className='panel'><div className='eyebrow'>WHATSAPP CONVERSATION</div><div className='list'>{loading?<div className='empty'>Loading conversations…</div>:conversations.length?conversations.map(c=><button className={'conv '+(c.id===selectedId?'active':'')} key={c.id} onClick={()=>setSelectedId(c.id)}><strong>{c.contact_name||c.phone}</strong><small>{c.phone} · {c.service_window_open?'24h window open':'Template required'}</small></button>):<div className='empty'>No conversations.</div>}</div>{selected&&<div style={{marginTop:11}}>{selected.service_window_open?<span className='pill'>Ready to send</span>:<span className='pill' style={{background:'#fff7e9',color:'#8b5e11'}}>Template required</span>}</div>}</section></div></div></AppShell>
}