'use client';
import {useEffect,useState} from 'react';

const css=`
.page{min-height:100vh;background:#f6fafb;padding:24px 14px 60px;color:#17202b}.shell{max-width:1100px;margin:auto;display:grid;gap:14px}.hero{background:#fff;border:1px solid #e1e8ec;border-radius:20px;padding:20px}.hero h1{margin:0}.hero p{margin:5px 0;color:#7d8992;font-size:10px}.toolbar{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}.pill{padding:7px 9px;border-radius:999px;background:#edf5ff;color:#2166d1;font-size:9px;font-weight:900}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.product{background:#fff;border:1px solid #e1e8ec;border-radius:16px;overflow:hidden}.photo{height:150px;background:#eef4f6;overflow:hidden}.photo img{width:100%;height:100%;object-fit:cover}.body{padding:14px}.body h3{margin:0;font-size:12px}.body p{font-size:9px;color:#7d8992;line-height:1.5}.price{font-size:12px;font-weight:950}.old{margin-left:7px;color:#98a1a9;text-decoration:line-through;font-size:9px}.actions{display:flex;gap:6px;margin-top:10px}.btn{flex:1;border:1px solid #dce5e9;border-radius:9px;padding:9px 8px;background:#fff;font-size:9px;font-weight:900;cursor:pointer}.primary{background:#2168c9;color:#fff;border-color:#2168c9}.wish{max-width:42px}.section{background:#fff;border:1px solid #e1e8ec;border-radius:16px;padding:16px}.section h2{margin:0;font-size:14px}.cartrow{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-top:1px solid #edf0f3;font-size:10px}.empty{padding:24px;text-align:center;color:#7d8992;font-size:10px}.message{padding:9px 11px;border-radius:9px;background:#edf9f4;color:#087f5c;font-size:9px}.error{padding:9px 11px;border-radius:9px;background:#fff1f2;color:#9f1239;font-size:9px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.grid{grid-template-columns:1fr}}
`;
function session(){let k=localStorage.getItem('catalog_session_key');if(!k){k=crypto.randomUUID();localStorage.setItem('catalog_session_key',k)}return k}
export default function PublicCatalog({params}:{params:{slug:string}}){
 const[data,setData]=useState<any>({workspace:null,categories:[],products:[],cart:[],wishlist:[]}),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function load(){try{const r=await fetch('/api/public/catalog?slug='+encodeURIComponent(params.slug)+'&sessionKey='+encodeURIComponent(session()),{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Catalogue not found.');setData(d)}catch(e){setError(e instanceof Error?e.message:'Catalogue not found.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[params.slug]);
 async function action(actionType:string,productId:string){setMessage('');setError('');try{const r=await fetch('/api/public/catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug:params.slug,sessionKey:session(),productId,action:actionType,quantity:1})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to update.');setMessage(actionType==='wishlist_toggle'?(d.wishlisted?'Added to wishlist.':'Removed from wishlist.'):'Added to cart.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update.')}}
 const cartTotal=(data.cart||[]).reduce((sum:any,row:any)=>sum+Number(row.quantity||0)*Number(row.catalog_products?.price||0),0);
 if(loading)return <main className='page'><div className='shell'><div className='hero'>Loading catalogue…</div></div></main>;
 if(error&&!data.workspace)return <main className='page'><div className='shell'><div className='error'>{error}</div></div></main>;
 return <main className='page'><style>{css}</style><div className='shell'><section className='hero'><div className='toolbar'><div><h1>{data.workspace?.name||'Catalogue'}</h1><p>Products, offers, wishlist and cart.</p></div><span className='pill'>Cart ₹{cartTotal.toFixed(2)}</span></div>{message&&<div className='message' style={{marginTop:10}}>{message}</div>}</section><section className='grid'>{data.products.map((p:any)=><article className='product' key={p.id}><div className='photo'>{p.image_url&&<img src={p.image_url} alt=''/ >}</div><div className='body'><h3>{p.name}</h3><p>{p.description||'Catalogue product'}</p><div><span className='price'>₹{Number(p.price||0).toFixed(2)}</span>{p.compare_at_price!=null&&<span className='old'>₹{Number(p.compare_at_price).toFixed(2)}</span>}</div><div className='actions'><button className='btn primary' onClick={()=>void action('cart_add',p.id)}>Add to Cart</button><button className='btn wish' onClick={()=>void action('wishlist_toggle',p.id)} aria-label='Toggle wishlist'>{(data.wishlist||[]).includes(p.id)?'♥':'♡'}</button></div></div></article>)}</section><section className='section'><h2>Cart</h2>{data.cart?.length?<div style={{marginTop:8}}>{data.cart.map((row:any,i:number)=><div className='cartrow' key={i}><span>{row.catalog_products?.name} × {row.quantity}</span><strong>₹{(Number(row.quantity||0)*Number(row.catalog_products?.price||0)).toFixed(2)}</strong></div>)}</div>:<div className='empty'>Your cart is empty.</div>}</section></div></main>
}