'use client';
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';
type Keyword={id:string;keyword:string;category:string|null;active:boolean;created_at:string};
export default function KeywordsPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[items,setItems]=useState<Keyword[]>([]),[keyword,setKeyword]=useState(''),[category,setCategory]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function load(id:string){const r=await getSupabase().from('workspace_keywords').select('id,keyword,category,active,created_at').eq('workspace_id',id).order('created_at',{ascending:false});if(r.error)throw r.error;setItems((r.data||[]) as Keyword[])}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);if(id)load(id).catch(e=>setError(e instanceof Error?e.message:'Unable to load keywords.'))},[]);
 async function add(){setBusy('add');setError('');try{const value=keyword.trim();if(!value)throw Error('Enter a keyword.');const r=await getSupabase().from('workspace_keywords').insert({workspace_id:workspaceId,keyword:value,category:category.trim()||null,active:true}).select('id').single();if(r.error)throw r.error;setKeyword('');setCategory('');await load(workspaceId)}catch(e){setError(e instanceof Error?e.message:'Unable to add keyword.')}finally{setBusy('')}}
 async function toggle(x:Keyword){setBusy(x.id);setError('');try{const r=await getSupabase().from('workspace_keywords').update({active:!x.active}).eq('id',x.id).eq('workspace_id',workspaceId);if(r.error)throw r.error;await load(workspaceId)}catch(e){setError(e instanceof Error?e.message:'Unable to update keyword.')}finally{setBusy('')}}
 async function remove(x:Keyword){if(!confirm('Remove '+x.keyword+' from this workspace?'))return;setBusy(x.id);setError('');try{const r=await getSupabase().from('workspace_keywords').delete().eq('id',x.id).eq('workspace_id',workspaceId);if(r.error)throw r.error;await load(workspaceId)}catch(e){setError(e instanceof Error?e.message:'Unable to remove keyword.')}finally{setBusy('')}}
 return <AppShell title='Google Business & Reviews'><style jsx>{`.page{display:grid;gap:16px}.form{padding:20px}.grid{display:grid;grid-template-columns:1.5fr 1fr auto;gap:10px}.field{display:grid;gap:6px}.field label{font-size:10px;font-weight:850;color:#475467}.field input{border:1px solid #dbe4e8;border-radius:10px;padding:11px 12px;min-height:42px}.row{display:grid;grid-template-columns:minmax(0,1fr) 160px 90px 90px;gap:12px;padding:14px 18px;border-top:1px solid #edf0f3;align-items:center}.row strong{font-size:11px}.row small{display:block;color:#8a95a3;font-size:9px;margin-top:3px}.tag{font-size:9px;font-weight:900}.on{color:#14804a}.off{color:#8a95a3}.empty{padding:40px;text-align:center;color:#667085;font-size:11px}@media(max-width:800px){.grid,.row{grid-template-columns:1fr}}`}</style><div className='page'><div className='page-head'><div><div className='eyebrow'>KEYWORDS MANAGEMENT</div><h1>Workspace Keywords</h1><p>These keywords are supplied to review-response generation when they fit naturally.</p></div></div>{error&&<div className='alert alert-error'>{error}</div>}<section className='panel form'><div className='grid'><div className='field'><label>Keyword</label><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder='e.g. hygiene, service, quality'/></div><div className='field'><label>Category</label><input value={category} onChange={e=>setCategory(e.target.value)} placeholder='product, service, brand'/></div><button className='btn btn-primary' disabled={busy==='add'} onClick={()=>void add()}>{busy==='add'?'Adding…':'Add Keyword'}</button></div></section><section className='panel'><div className='panel-head'><div><div className='eyebrow'>ACTIVE LIBRARY</div><h2>Keywords</h2></div></div>{items.length===0?<div className='empty'>No workspace keywords yet.</div>:items.map(x=><div className='row' key={x.id}><div><strong>{x.keyword}</strong><small>{x.category||'No category'}</small></div><div><span className={'tag '+(x.active?'on':'off')}>{x.active?'ACTIVE':'PAUSED'}</span></div><div><button className='btn btn-soft' disabled={busy===x.id} onClick={()=>void toggle(x)}>{x.active?'Pause':'Activate'}</button></div><div><button className='btn btn-soft' style={{color:'#b42318'}} disabled={busy===x.id} onClick={()=>void remove(x)}>Remove</button></div></div>)}</section></div></AppShell>
}