export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      brands: { Row: { id: string; name: string; slug: string; logo_url: string | null; user_id: string; created_at: string; updated_at: string }; Insert: { id?: string; name: string; slug: string; logo_url?: string | null; user_id: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['brands']['Insert']>; Relationships: [] };
      post_drafts: { Row: { id: string; brand_id: string; user_id: string; title: string | null; message: string | null; media_urls: string[]; platforms: string[]; scheduled_at: string | null; status: string; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['post_drafts']['Row'], 'id'|'created_at'|'updated_at'> & Partial<Pick<Database['public']['Tables']['post_drafts']['Row'],'id'|'created_at'|'updated_at'>>; Update: Partial<Database['public']['Tables']['post_drafts']['Insert']>; Relationships: [] };
      publishing_history: { Row: { id: string; user_id: string; brand_id: string | null; draft_id: string | null; social_account_id: string | null; platform: string; platform_post_id: string | null; message: string | null; status: string; error_message: string | null; published_at: string | null; created_at: string }; Insert: Partial<Database['public']['Tables']['publishing_history']['Row']> & Pick<Database['public']['Tables']['publishing_history']['Row'],'user_id'|'platform'|'status'>; Update: Partial<Database['public']['Tables']['publishing_history']['Insert']>; Relationships: [] };
      scheduled_posts: { Row: { id: string; user_id: string; brand_id: string; account_ids: string[]; caption: string; media_url: string | null; link: string | null; scheduled_for: string; status: string; attempts: number; last_error: string | null; published_at: string | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; brand_id: string; account_ids?: string[]; caption?: string; media_url?: string | null; link?: string | null; scheduled_for: string; status?: string; attempts?: number; last_error?: string | null; published_at?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['scheduled_posts']['Insert']>; Relationships: [] };
      social_accounts: { Row: { id: string; user_id: string; brand_id: string | null; name: string; platform: string; platform_account_id: string; access_token: string | null; refresh_token: string | null; status: string; handle: string | null; token_expires_at: string | null; token_checked_at: string | null; token_error: string | null; token_last_refreshed_at: string | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; brand_id?: string | null; name: string; platform: string; platform_account_id: string; access_token?: string | null; refresh_token?: string | null; status?: string; handle?: string | null; token_expires_at?: string | null; token_checked_at?: string | null; token_error?: string | null; token_last_refreshed_at?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['social_accounts']['Insert']>; Relationships: [] };
      social_posts: { Row: { id: string; user_id: string; social_account_id: string | null; platform: string; platform_post_id: string | null; message: string; link: string | null; media_type: string; status: string; published_at: string | null; attempted_at: string | null; error_message: string | null; platform_response: Json | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; social_account_id?: string | null; platform: string; platform_post_id?: string | null; message?: string; link?: string | null; media_type?: string; status?: string; published_at?: string | null; attempted_at?: string | null; error_message?: string | null; platform_response?: Json | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['social_posts']['Insert']>; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};