'use client';

import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

type Flow={id:string;name:string;description:string|null;default_locale:string;supported_locales:string[];trigger_type:string;trigger_config:any;steps:any[];active:boolean;priority:number;updated_at:string};

const starter=[
  {id:'welcome',type:'buttons',message:{en:'Hi! How can we help you today?',gu:'નમસ્તે! આજે અમે તમને કેવી રીતે મદદ કરી શકીએ?',hi:'नमस्ते! आज हम आपकी कैसे मदद कर सकते हैं?'},buttons:[
    {id:'products',title:{en:'View Products',gu:'Products જુઓ',hi:'Products देखें'},next_step_id:'products'},
    {id:'price',title:{en:'Get Price',gu:'ભાવ મેળવો',hi:'कीमत जानें'},next_step_id:'price'},
    {id:'human',title:{en:'Talk to Team',gu:'Team સાથે વાત',hi:'Team से बात'},next_step_id:'handoff'}
  ]},
  {id:'products',type:'product_suggestions',message:{en:'Here are some products that may fit your need:',gu:'તમારી જરૂરિયાત માટે કેટલાક products અહીં છે:',hi:'आपकी जरूरत के लिए कुछ products यहाँ हैं:'},empty_message:{en:'I could not find a close product match. Our team can help.',gu:'મને નજીકનો product match મળ્યો નથી. અમારી team મદદ કરશે.',hi:'मुझे सही product match नहीं मिला। हमारी team मदद करेगी।'},query:'' ,next_step_id:'handoff'},
  {id:'price',type:'collect',variable_name:'requirement',message:{en:'Tell me what you need and I will help with the right option.',gu:'તમને શું જોઈએ છે તે કહો, અમે યોગ્ય option બતાવીશું.',hi:'आपको क्या चाहिए बताइए, हम सही option सुझाएँगे।'},next_step_id:'handoff'},
  {id:'handoff',type:'handoff',message:{en:'Thanks! I am passing this to our team now.',gu:'આભાર! હવે હું તમારી વાત અમારી team સુધી પહોંચાડું છું.',hi:'धन्यवाद! मैं अब आपकी बात हमारी team तक भेज रहा हूँ।'}}
];

const css=`
.page{display:grid;gap:14px}.head{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;flex-wrap:wrap}.head h1{margin:5px 0}.head p{margin:0;color:#73818b;font-size:10px}.grid{display:grid;grid-template-columns:340px minmax(0,1fr);gap:14px}.panel{padding:17px;overflow:hidden}.form{display:grid;gap:9px}.field{display:grid;gap:5px;font-size:9px;font-weight:900}.input,.select,.textarea{width:100%;box-sizing:border-box;padding:9px 10px;border:1px solid #dce5e9;border-radius:9px;background:#fff;font-size:10px}.textarea{min-height:360px;resize:vertical;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:9px;line-height:1.5}.btn{border:1px solid #dce5e9;border-radius:9px;padding:9px 11px;background:#fff;font-size:9px;font-weight:900;cursor:pointer}.primary{background:#17202b;color:#fff;border-color:#17202b}.soft{background:#edf9f7;color:#087f7b;border-color:#d2eee9}.notice,.error{padding:10px 12px;border-radius:9px;font-size:10px}.notice{background:#fff;border:1px solid #dce5e9}.error{background:#fff1f2;border:1px solid #f5c8cf;color:#9f1239}.rows{display:grid;gap:7px;margin-top:11px}.row{border:1px solid #e1e8eb;border-radius:11px;padding:10px;display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:8px;align-items:center}.row strong{font-size:10px}.row small{display:block;color:#859199;font-size:8px;margin-top:3px}.badge{display:inline-flex;padding:5px 7px;border-radius:999px;background:#edf9f1;color:#087443;font-size:8px;font-weight:900}.orange{background:#fff7e9;color:#8b5e11}.muted{color:#7d8992;font-size:9px;line-height:1.5}.code-note{padding:9px 10px;border:1px dashed #cddbe0;border-radius:9px;background:#fbfcfd;font-size:9px;color:#6f7d86;word-break:break-all}@media(max-width:900px){.grid{grid-template-columns:1fr}}
`;

export default function WhatsAppBotFlowsPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[flows,setFlows]=useState<Flow[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[editingId,setEditingId]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const[form,setForm]=useState({name:'',description:'',default_locale:'en',supported_locales:'en,gu,hi',trigger_type:'keyword',keywords:'hi, hello, help, price, product',priority:'100',steps:JSON.stringify(starter,null,2)});
 async function token(){const s=(await getSupabase().auth.getSession()).data.session;if(!s)throw new Error('Session expired');return s.access_token}
 async function load(id=workspaceId){if(!id)return;setLoading(true);setError('');try{const t=await token();const r=await fetch('/api/whatsapp/bot-flows?workspaceId='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+t},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to load bot flows.');setFlows(d.flows||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load bot flows.')}finally{setLoading(false)}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);if(id)void load(id);else setLoading(false);const onWorkspace=(e:Event)=>{const next=(e as CustomEvent<{workspaceId?:string}>).detail?.workspaceId||'';if(next&&next!==id){id=next;setWorkspaceId(next);setEditingId('');void load(next)}};window.addEventListener('mdsm:workspace-changed',onWorkspace);return()=>window.removeEventListener('mdsm:workspace-changed',onWorkspace)},[]);
 function reset(){setEditingId('');setForm({name:'',description:'',default_locale:'en',supported_locales:'en,gu,hi',trigger_type:'keyword',keywords:'hi, hello, help, price, product',priority:'100',steps:JSON.stringify(starter,null,2)})}
 function edit(flow:Flow){setEditingId(flow.id);setForm({name:flow.name,description:flow.description||'',default_locale:flow.default_locale,supported_locales:(flow.supported_locales||[]).join(','),trigger_type:flow.trigger_type,keywords:Array.isArray(flow.trigger_config?.keywords)?flow.trigger_config.keywords.join(', '):'',priority:String(flow.priority||100),steps:JSON.stringify(flow.steps||[],null,2)});window.scrollTo({top:400,behavior:'smooth'})}
 async function save(){setSaving(true);setNotice('');setError('');try{const steps=JSON.parse(form.steps);if(!Array.isArray(steps))throw new Error('Steps JSON must be an array.');const payload={workspaceId,name:form.name,description:form.description,default_locale:form.default_locale,supported_locales:form.supported_locales.split(',').map(x=>x.trim()).filter(Boolean),trigger_type:form.trigger_type,trigger_config:{keywords:form.keywords.split(',').map(x=>x.trim()).filter(Boolean)},priority:Number(form.priority),steps,active:true};const t=await token();const r=await fetch('/api/whatsapp/bot-flows',{method:editingId?'PATCH':'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify(editingId?{...payload,id:editingId}:payload)});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to save bot flow.');setNotice(editingId?'Bot flow updated.':'Bot flow created.');reset();await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save bot flow.')}finally{setSaving(false)}}
 async function toggle(flow:Flow){setSaving(true);try{const t=await token();const r=await fetch('/api/whatsapp/bot-flows',{method:'PATCH',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,id:flow.id,active:!flow.active})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to update flow.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update flow.')}finally{setSaving(false)}}
 async function remove(id:string){if(!confirm('Delete this bot flow? Active sessions will stop using it.'))return;setSaving(true);try{const t=await token();const r=await fetch('/api/whatsapp/bot-flows',{method:'DELETE',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,id})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to delete flow.');setNotice('Bot flow deleted.');if(editingId===id)reset();await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete flow.')}finally{setSaving(false)}}
 const webhookUrl=typeof window!=='undefined'?window.location.origin+'/api/whatsapp/webhook':'/api/whatsapp/webhook';
 return <AppShell title='WhatsApp Bot Automation'><style jsx>{css}</style><div className='page'>
  <div className='head'><div><div className='eyebrow'>WHATSAPP • BOT AUTOMATION</div><h1>Multilingual WhatsApp Bot Builder</h1><p>Build keyword, new-conversation and button-driven flows. Each step can contain localized messages for English, Gujarati, Hindi and other locales.</p></div><div style={{display:'flex',gap:7}}><button className='btn' onClick={()=>void load()}>↻ Refresh</button><button className='btn primary' onClick={()=>reset()}>＋ New Flow</button></div></div>
  {notice&&<div className='notice'>{notice}</div>}{error&&<div className='error'>{error}</div>}
  <div className='grid'>
   <section className='panel'><div className='eyebrow'>FLOW EDITOR</div><h2>{editingId?'Edit Bot Flow':'Create Bot Flow'}</h2><p className='muted'>Use the starter flow or edit the JSON steps for a fully customized bot.</p><div className='form' style={{marginTop:12}}><label className='field'>Flow name<input className='input' value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder='Sales Assistant'/></label><label className='field'>Description<input className='input' value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><label className='field'>Default locale<input className='input' value={form.default_locale} onChange={e=>setForm({...form,default_locale:e.target.value})}/></label><label className='field'>Supported locales<input className='input' value={form.supported_locales} onChange={e=>setForm({...form,supported_locales:e.target.value})}/></label></div><label className='field'>Trigger<select className='select' value={form.trigger_type} onChange={e=>setForm({...form,trigger_type:e.target.value})}><option value='keyword'>Keyword</option><option value='new_conversation'>New Conversation</option><option value='button_reply'>Button Reply</option><option value='any_message'>Any Message</option></select></label><label className='field'>Trigger keywords<input className='input' value={form.keywords} onChange={e=>setForm({...form,keywords:e.target.value})} placeholder='hello, hi, price, product'/></label><label className='field'>Priority<input className='input' type='number' value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}/></label><label className='field'>Steps JSON<textarea className='textarea' value={form.steps} onChange={e=>setForm({...form,steps:e.target.value})}/></label><div className='actions'><button className='btn soft' onClick={()=>setForm({...form,steps:JSON.stringify(starter,null,2)})}>Load Starter Flow</button>{editingId&&<button className='btn' onClick={reset}>Cancel Edit</button>}<button className='btn primary' disabled={saving||!form.name.trim()} onClick={()=>void save()}>{saving?'Saving…':editingId?'Update Flow':'Create Flow'}</button></div><div className='code-note'>Webhook endpoint: {webhookUrl}<br/>Verify token env: <strong>WHATSAPP_WEBHOOK_VERIFY_TOKEN</strong><br/>Signature secret env: <strong>WHATSAPP_APP_SECRET</strong></div></div></section>
   <section className='panel'><div className='eyebrow'>ACTIVE FLOWS</div><h2>Workspace Bot Flows</h2><p className='muted'>Priority is evaluated from low to high when a new message starts a flow.</p><div className='rows'>{loading?<div className='muted'>Loading flows…</div>:flows.length?flows.map(flow=><article className='row' key={flow.id}><div><strong>{flow.name}</strong><small>{flow.trigger_type} · {(flow.supported_locales||[]).join(', ')} · {flow.steps?.length||0} steps</small></div><span className={'badge '+(flow.active?'':'orange')}>{flow.active?'ACTIVE':'PAUSED'}</span><button className='btn' onClick={()=>edit(flow)}>Edit</button><button className='btn' disabled={saving} onClick={()=>void toggle(flow)}>{flow.active?'Pause':'Activate'}</button><button className='btn' disabled={saving} onClick={()=>void remove(flow.id)}>Delete</button></article>):<div className='muted'>No bot flows yet. Load the starter flow and create your first assistant.</div>}</div></section>
  </div>
 </div></AppShell>
}