'use client';
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

export default function NegativeFeedbackPage(){
 const[rows,setRows]=useState<any[]>([]),[settings,setSettings]=useState<any>(null),[error,setError]=useState('');
 async function load(id:string){setError('');try{const sb=getSupabase(),s=(await sb.auth.getSession()).data.session;if(!s){location.href='/login';return}const[a,r]=await Promise.all([fetch('/api/workspace-review-settings?workspace_id='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+s.access_token},cache:'no-store'}),sb.from('feedback_responses').select('id,customer_name,customer_email,rating,answers,sentiment,created_at').eq('workspace_id',id).order('created_at',{ascending:false}).limit(100)]);const ad=await a.json();if(!a.ok)throw Error(ad?.error||'Unable to load protection settings.');if(r.error)throw r.error;setSettings(ad.settings);setRows((r.data||[]).filter((x:any)=>Number(x.rating||0)<=Number(ad.settings?.negative_protection_threshold||2)))}catch(e){setError(e instanceof Error?e.message:'Unable to load negative feedback.')}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}if(id)void load(id)},[]);
 return <AppShell title='Negative Review Feedback'><style jsx>{".page{display:grid;gap:14px}.panel{padding:18px}.hero h1{margin:5px 0}.note{font-size:10px;color:#667085;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.metric span{display:block;font-size:9px;font-weight:900;color:#667085}.metric strong{display:block;font-size:24px;margin-top:5px}.row{padding:13px 0;border-top:1px solid #edf0f3}.tag{padding:5px 8px;border-radius:999px;background:#fff1f0;color:#b42318;font-size:8px;font-weight:900}.actions{display:flex;gap:7px;flex-wrap:wrap}.btn{border:1px solid #dbe4e8;background:#fff;border-radius:9px;padding:9px 11px;font-size:9px;font-weight:900;cursor:pointer}@media(max-width:800px){.grid{grid-template-columns:1fr}}"} </style><div className='page'><section className='panel hero'><div className='eyebrow'>NEGATIVE REVIEW FEEDBACK</div><h1>Low-rating feedback</h1><p className='note'>Use private follow-up for service recovery while keeping a clear genuine path for customers who choose to review publicly.</p></section>{error&&<div className='alert alert-error'>{error}</div>}<div className='grid'><article className='panel metric'><span>Protection</span><strong>{settings?.negative_protection_enabled?'ON':'OFF'}</strong></article><article className='panel metric'><span>Threshold</span><strong>{settings?.negative_protection_threshold||'—'}★</strong></article><article className='panel metric'><span>Low-rating feedback</span><strong>{rows.length}</strong></article></div><section className='panel'><div className='eyebrow'>FOLLOW-UP FEED</div><p className='note'>{settings?.negative_protection_message||'Configure the protection message in Settings.'}</p>{!rows.length?<p className='note'>No low-rating feedback responses found.</p>:rows.map(x=><article className='row' key={x.id}><div className='actions'><strong>{x.customer_name||'Anonymous customer'}</strong><span className='tag'>{x.rating||'—'}★</span><span className='note'>{x.customer_email||'No email'}</span></div><p className='note' style={{marginTop:5}}>{JSON.stringify(x.answers||{}).slice(0,600)}</p></article>)}<div className='actions' style={{marginTop:11}}><button className='btn' onClick={()=>location.href='/dashboard/settings#review-ai'}>Protection Settings →</button><button className='btn' onClick={()=>location.href='/dashboard/gmb/responses'}>Feedback Responses →</button></div></section></div></AppShell>
}
