'use client';
import {useEffect,useState} from 'react';
import {getSupabase} from '../../../../lib/supabase-browser';

type Draft={title:string;message:string;media_urls:string[]|null;platforms:string[]|null;brand_id:string};
type Approval={id:string;draft_id:string;workplace_id:string;submitted_by:string;status:string;reviewer_note:string|null;submitted_at:string;post_drafts?:Draft};
type ApprovalRow=Omit<Approval,'post_drafts'> & {post_drafts?:Draft|Draft[]|null};
export default function ApprovalsPage(){const[items,setItems]=useState<Approval[]>([]),[brands,setBrands]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('');
 async function load(){setLoading(true);setError('');try{const s=(await getSupabase().auth.getSession()).data.session;if(!s)throw new Error('Login required.');const a=await getSupabase().from('post_approvals').select('id,draft_id,workplace_id,submitted_by,status,reviewer_note,submitted_at,post_drafts(title,message,media_urls,platforms,brand_id)').eq('status','pending').order('submitted_at',{ascending:false});if(a.error)throw a.error;const b=await getSupabase().from('brands').select('id,name');if(b.error)throw b.error;const map:Record<string,string>={};(b.data||[]).forEach(x=>map[x.id]=x.name);setBrands(map);const rows=(a.data||[]) as unknown as ApprovalRow[];setItems(rows.map(({post_drafts,...rest})=>({...rest,post_drafts:Array.isArray(post_drafts)?post_drafts[0]:post_drafts||undefined})))}catch(e){setError(e instanceof Error?e.message:'Unable to load approvals.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function review(item:Approval,status:'approved'|'rejected'|'changes_requested'){setBusy(item.id);setError('');try{const s=(await getSupabase().auth.getSession()).data.session;if(!s)throw new Error('Login required.');const{data:u}=await getSupabase().auth.getUser();if(!u.user)throw new Error('Login required.');const{error:e}=await getSupabase().from('post_approvals').update({status,reviewed_by:u.user.id,reviewed_at:new Date().toISOString()}).eq('id',item.id);if(e)throw e;const draftStatus=status==='approved'?'approved':status==='changes_requested'?'changes_requested':'rejected';const{error:de}=await getSupabase().from('post_drafts').update({approval_status:draftStatus,approved_by:status==='approved'?u.user.id:null,approved_at:status==='approved'?new Date().toISOString():null}).eq('id',item.draft_id);if(de)throw de;await load()}catch(e){setError(e instanceof Error?e.message:'Unable to review post.')}finally{setBusy('')}}
 if(loading)return <main className="auth-page"><div className="muted">Loading approvals…</div></main>;
 return <main className="app-shell"><section className="main-shell" style={{width:'100%'}}><header className="main-header"><strong>Approval Center</strong><button onClick={()=>void load()}>↻ Refresh</button></header><div className="dashboard-content"><h1>Pending Approval</h1><p className="muted">Review staff posts before anything is published.</p>{error?<div className="data-warning">{error}</div>:null}{items.length?items.map(i=><article className="recent-card" style={{marginTop:20,padding:22}} key={i.id}><div className="section-head"><div><span>{brands[i.workplace_id]||'Workspace'}</span><h2>{i.post_drafts?.title||'Untitled Post'}</h2></div><em>Pending</em></div><p style={{whiteSpace:'pre-wrap',lineHeight:1.6}}>{i.post_drafts?.message||'No caption provided.'}</p>{i.post_drafts?.platforms?.length?<p className="muted">Platforms: {i.post_drafts.platforms.join(', ')}</p>:null}<div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:16}}><button className="primary-btn" disabled={busy===i.id} onClick={()=>void review(i,'approved')}>{busy===i.id?'…':'✓ Approve'}</button><button disabled={busy===i.id} onClick={()=>void review(i,'changes_requested')}>✎ Request Changes</button><button disabled={busy===i.id} onClick={()=>void review(i,'rejected')}>✕ Reject</button></div></article>):<div className="empty-state"><strong>No posts waiting for approval.</strong><span>When staff submit a post, it will appear here before publishing.</span></div>}</div></section></main>}
