'use client';
import { useEffect,useState } from 'react';
import AppShell from '../components/AppShell';
import { getSupabase } from '../../../lib/supabase-browser';

type Account={id:string;platform:string;name:string;handle:string|null;status:string}; type FacebookPage={id:string;name:string;handle:string|null};
export default function AccountsPage(){
 const [accounts,setAccounts]=useState<Account[]>([]),[pages,setPages]=useState<FacebookPage[]>([]),[selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 async function load(){const c=getSupabase();const{data:{user}}=await c.auth.getUser();if(!user){location.href='/login';return}const{data,error}=await c.from('social_accounts').select('id,platform,name,handle,status').eq('user_id',user.id).order('created_at',{ascending:false});if(error)setError(error.message);else setAccounts((data||[]) as Account[]);setLoading(false)}
 useEffect(()=>{const p=new URLSearchParams(location.search);if(p.get('error'))setError(p.get('error')||'');if(p.get('facebook')==='connected')loadPages();load()},[]);
 async function loadPages(){setBusy(true);try{const r=await fetch('/api/meta/facebook/pages',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load Pages');setPages(d.pages||[]);if(d.pages?.length===1)setSelected(d.pages[0].id)}catch(e){setError(e instanceof Error?e.message:'Unable to load Pages')}finally{setBusy(false)}}
 async function connectFacebook(){if(!selected){setError('Please select a Facebook Page.');return}setBusy(true);try{const{data:{session}}=await getSupabase().auth.getSession();const r=await fetch('/api/meta/facebook/connect',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({pageId:selected})}),d=await r.json();if(!r.ok)throw Error(d.error||'Connection failed');setSuccess(`Connected ${d.page?.name||'Facebook Page'} successfully.`);setPages([]);setSelected('');await load()}catch(e){setError(e instanceof Error?e.message:'Connection failed')}finally{setBusy(false)}}
 async function syncInstagram(){setBusy(true);setError('');try{const{data:{session}}=await getSupabase().auth.getSession();const r=await fetch('/api/meta/instagram/sync',{method:'POST',headers:{Authorization:`Bearer ${session?.access_token||''}`}}),d=await r.json();if(!r.ok)throw Error(d.error||'Instagram sync failed');setSuccess(d.connected?`Connected ${d.connected} Instagram Business account${d.connected===1?'':'s'}.`:d.skipped?.join(' · ')||'No linked Instagram Business account found.');await load()}catch(e){setError(e instanceof Error?e.message:'Instagram sync failed')}finally{setBusy(false)}}
 async function connectGoogle(){setBusy(true);setError('');try{const{data:{session}}=await getSupabase().auth.getSession();if(!session?.access_token)throw Error('Your session has expired.');const r=await fetch('/api/google/business/login',{headers:{Authorization:`Bearer ${session.access_token}`},redirect:'manual'});if(r.type==='opaqueredirect'||r.status===0){window.location.href='/api/google/business/login';return}if(!r.ok&&r.status!==307) {const d=await r.json().catch(()=>({}));throw Error(d.error||'Google Business OAuth is not configured.')}const locationHeader=r.headers.get('location');if(locationHeader)window.location.href=locationHeader;else window.location.href='/api/google/business/login'}catch(e){setError(e instanceof Error?e.message:'Google Business connection failed.');setBusy(false)}}
 const has=(p:string)=>accounts.some(a=>a.platform===p&&a.status==='connected');
 return <AppShell title="Accounts"><div className="page-head"><div><span className="eyebrow">CHANNELS</span><h1>Connected Accounts</h1><p>Connect Facebook, Instagram Business and Google Business Profile accounts.</p></div><button className="btn btn-primary" onClick={()=>location.href='/api/meta/facebook/login'}>＋ Connect Facebook</button></div>
 {error&&<div className="alert alert-error">⚠ {error}<button onClick={()=>setError('')}>×</button></div>}{success&&<div className="alert alert-success">✓ {success}</div>}
 <div className="account-platform-grid"><Platform icon="f" tone="facebook" title="Facebook" text="Pages, publishing and account management." connected={has('facebook')} action={()=>location.href='/api/meta/facebook/login'}/><Platform icon="◎" tone="instagram" title="Instagram" text="Business account publishing and insights." connected={has('instagram')} action={syncInstagram}/><Platform icon="G" tone="google" title="Google Business" text="Business Profile updates and locations." connected={has('google_business')} action={connectGoogle}/></div>
 {pages.length>0&&<section className="panel connect-panel"><div><span className="eyebrow">META BUSINESS</span><h2>Select Facebook Page</h2><p>Choose which Page you want MD Hygiene Social Manager to manage.</p></div><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select a Page…</option>{pages.map(p=><option key={p.id} value={p.id}>{p.name}{p.handle?` (@${p.handle})`:''}</option>)}</select><button className="btn btn-primary" disabled={!selected||busy} onClick={connectFacebook}>{busy?'Connecting…':'Connect Selected Page'}</button></section>}
 <section className="panel"><div className="panel-head"><div><span className="eyebrow">YOUR CHANNELS</span><h2>Connected accounts</h2></div><span className="count-badge">{accounts.length} connected</span></div>{loading?<div className="empty-state">Loading accounts…</div>:accounts.length===0?<div className="empty-state"><div className="empty-icon">◎</div><h3>No accounts connected</h3><p>Connect your social channels to load live metrics and publish.</p><button className="btn btn-primary" onClick={()=>location.href='/api/meta/facebook/login'}>Connect Facebook</button></div>:<div className="account-list">{accounts.map(a=><div className="account-row" key={a.id}><div className={`account-avatar ${a.platform}`}>{a.platform==='facebook'?'f':a.platform==='instagram'?'◎':'G'}</div><div className="account-info"><strong>{a.name}</strong><span>{a.handle?`@${a.handle}`:a.platform.replace('_',' ')}</span></div><span className="connected-pill">● Connected</span><button className="btn btn-soft" onClick={()=>location.href=`/dashboard/publish?accountId=${a.id}`}>Create Post →</button></div>)}</div>}</section></AppShell>}
function Platform({icon,tone,title,text,connected,action}:{icon:string;tone:string;title:string;text:string;connected:boolean;action:()=>void}){return <article className="platform-card"><div className={`platform-icon ${tone}`}>{icon}</div><div className="platform-title"><div><h2>{title}</h2><span>{text}</span></div><span className={connected?'connected-pill':'soon-pill'}>{connected?'Connected':'Connect'}</span></div><button className="btn btn-soft" onClick={action}>{connected?'Manage / Sync':'Connect'} <b>→</b></button></article>}
