'use client';
import {useEffect,useState} from 'react';
import AppShell from '../components/AppShell';
import {getSupabase} from '../../../lib/supabase-browser';

const css=`
.page{display:grid;gap:14px}.hero{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;flex-wrap:wrap}.hero h1{margin:5px 0}.hero p{margin:0;color:#718096;font-size:11px;max-width:760px}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.panel{min-width:0}.form{display:grid;gap:10px;padding:17px}.field{display:grid;gap:5px}.field span{font-size:8px;text-transform:uppercase;letter-spacing:.08em;color:#667085;font-weight:900}.input{width:100%;border:1px solid #dce5e9;border-radius:9px;padding:10px 11px;font-size:10px;background:#fff}.textarea{min-height:82px;resize:vertical}.actions{display:flex;gap:7px;flex-wrap:wrap}.btn{border:1px solid #dce5e9;border-radius:9px;padding:9px 11px;background:#fff;font-size:9px;font-weight:900;cursor:pointer}.primary{background:#2168c9;color:#fff;border-color:#2168c9}.soft{background:#eef5ff;color:#2166d1}.section{overflow:hidden}.section-head{padding:16px 17px}.section-head h2{margin:4px 0;font-size:15px}.section-head p{margin:4px 0;color:#7d8992;font-size:9px}
.rows{padding:0 17px 12px}.row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:11px 0;border-top:1px solid #edf0f3;align-items:center}.row strong{font-size:10px}.row small{display:block;color:#88939c;font-size:8px;margin-top:3px}.tag{font-size:8px;padding:5px 7px;border-radius:999px;background:#f2f5f7;color:#667085;font-weight:900}.preview{padding:18px;background:linear-gradient(135deg,#eff8ff,#f7fbfb);border:1px solid #dfe9ed;border-radius:16px}.cover{height:120px;border-radius:13px;background:#dfeef1;overflow:hidden}.cover img{width:100%;height:100%;object-fit:cover}.identity{display:flex;gap:12px;align-items:flex-end;margin-top:-28px;position:relative;padding:0 11px}.avatar{width:76px;height:76px;border-radius:20px;background:#fff;border:4px solid #fff;display:grid;place-items:center;overflow:hidden;font-weight:950;color:#2168c9;font-size:20px}.avatar img{width:100%;height:100%;object-fit:cover}.preview h2{margin:10px 0 3px}.preview p{margin:0;color:#667085;font-size:10px;line-height:1.5}
@media(max-width:900px){.grid{grid-template-columns:1fr}}
`;
type Data={card:any;contacts:any[];socialLinks:any[];services:any[];testimonials:any[];embeds:any[];payments:any[]};

export default function DigitalCardPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[data,setData]=useState<Data>({card:null,contacts:[],socialLinks:[],services:[],testimonials:[],embeds:[],payments:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const[card,setCard]=useState({full_name:'',business_name:'',bio:'',profile_picture_url:'',cover_image_url:'',logo_url:'',profile_slug:'',about_us:'',offline_content:'',embed_content:'',lead_capture_enabled:true,contact_form_enabled:true,payment_url:''});
 const[contact,setContact]=useState({label:'',value:'',kind:'phone'}),[service,setService]=useState({name:'',description:'',price:''}),[testimonial,setTestimonial]=useState({customer_name:'',quote:'',rating:'5'}),[social,setSocial]=useState({platform:'Instagram',url:''}),[embed,setEmbed]=useState({title:'',embed_code:''});
 async function token(){const s=(await getSupabase().auth.getSession()).data.session;if(!s){location.href='/login';throw new Error('Session expired.')}return s.access_token}
 async function load(id:string){setLoading(true);setError('');try{const t=await token();const r=await fetch('/api/digital-card?workspaceId='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+t},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to load digital card.');setData(d);if(d.card)setCard({...card,...d.card})}catch(e){setError(e instanceof Error?e.message:'Unable to load digital card.')}finally{setLoading(false)}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);const onWorkspace=(e:Event)=>{const next=(e as CustomEvent<{workspaceId?:string}>).detail?.workspaceId||'';if(next&&next!==id){id=next;setWorkspaceId(next);void load(next)}};window.addEventListener('mdsm:workspace-changed',onWorkspace);if(id)void load(id);else setLoading(false);return()=>window.removeEventListener('mdsm:workspace-changed',onWorkspace)},[]);
 async function save(){setBusy(true);setError('');try{const t=await token();const r=await fetch('/api/digital-card',{method:'PATCH',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,...card,contacts:data.contacts,socialLinks:data.socialLinks,services:data.services,testimonials:data.testimonials,embeds:data.embeds,payments:data.payments})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to save digital card.');await load(workspaceId)}catch(e){setError(e instanceof Error?e.message:'Unable to save digital card.')}finally{setBusy(false)}}
 function add(type:string,item:any){setData(d=>({...d,[type]:[...(d as any)[type],item]}))}
 function previewUrl(){return card.profile_slug?'/digital-card/'+encodeURIComponent(card.profile_slug):''}
 return <AppShell title='Digital Card'><style>{css}</style><div className='page'>
  <div className='hero'><div className='page-head'><div className='eyebrow'>DIGITAL CARD</div><h1>Digital Business Card</h1><p>Profile, contact methods, social links, testimonials, services, lead capture, embeds, offline content and payment link for this workspace.</p></div><div className='actions'><button className='btn soft' onClick={()=>location.href='/dashboard'}>← Dashboard</button>{card.profile_slug&&<button className='btn' onClick={()=>location.href=previewUrl()}>Open Public Card →</button>}</div></div>
  {error&&<div className='alert alert-error'>{error}</div>}
  <section className='grid'>
   <section className='panel section'><div className='section-head'><div><div className='eyebrow'>PROFILE</div><h2>Profile & Business Identity</h2><p>Picture, cover, full name, business name, bio and logo.</p></div></div><div className='form'><label className='field'><span>Full Name</span><input className='input' value={card.full_name} onChange={e=>setCard({...card,full_name:e.target.value})}/></label><label className='field'><span>Business Name</span><input className='input' value={card.business_name} onChange={e=>setCard({...card,business_name:e.target.value})}/></label><label className='field'><span>Bio</span><textarea className='input textarea' value={card.bio} onChange={e=>setCard({...card,bio:e.target.value})}/></label><label className='field'><span>Profile Picture URL</span><input className='input' value={card.profile_picture_url} onChange={e=>setCard({...card,profile_picture_url:e.target.value})}/></label><label className='field'><span>Cover Image URL</span><input className='input' value={card.cover_image_url} onChange={e=>setCard({...card,cover_image_url:e.target.value})}/></label><label className='field'><span>Business Logo URL</span><input className='input' value={card.logo_url} onChange={e=>setCard({...card,logo_url:e.target.value})}/></label><label className='field'><span>Public Profile Slug</span><input className='input' value={card.profile_slug} onChange={e=>setCard({...card,profile_slug:e.target.value})} placeholder='md-hygiene'/></label></div></section>
   <section className='panel preview'><div className='eyebrow'>LIVE PREVIEW</div><div className='cover'>{card.cover_image_url&&<img src={card.cover_image_url} alt=''/>}</div><div className='identity'><div className='avatar'>{card.profile_picture_url?<img src={card.profile_picture_url} alt='' />:(card.business_name||card.full_name||'DC').slice(0,2).toUpperCase()}</div></div><h2>{card.full_name||'Your Name'}</h2><p><strong>{card.business_name||'Business Name'}</strong></p><p>{card.bio||'Your digital business card bio will appear here.'}</p><div className='actions' style={{marginTop:12}}>{card.lead_capture_enabled&&<span className='tag'>Lead Capture</span>} {card.contact_form_enabled&&<span className='tag'>Contact Form</span>} {card.payment_url&&<span className='tag'>Payment</span>}</div></section>
  </section>
  <section className='panel section'><div className='section-head'><div><div className='eyebrow'>CONTACT METHODS</div><h2>Unlimited Contact Methods</h2><p>Add phone, WhatsApp, email, website or custom contact methods.</p></div></div><div className='form'><div className='grid'><input className='input' placeholder='Label' value={contact.label} onChange={e=>setContact({...contact,label:e.target.value})}/><input className='input' placeholder='Value' value={contact.value} onChange={e=>setContact({...contact,value:e.target.value})}/></div><button className='btn primary' onClick={()=>{if(contact.label&&contact.value)add('contacts',contact);setContact({label:'',value:'',kind:'phone'})}}>Add Contact</button></div><div className='rows'>{data.contacts.map((x:any,i:number)=><div className='row' key={i}><div><strong>{x.label}</strong><small>{x.value}</small></div><span className='tag'>{x.kind||'custom'}</span></div>)}</div></section>
  <section className='grid'>
   <section className='panel section'><div className='section-head'><div><div className='eyebrow'>SOCIAL MEDIA</div><h2>Social Media Links</h2><p>Add unlimited profile links.</p></div></div><div className='form'><div className='grid'><input className='input' placeholder='Platform' value={social.platform} onChange={e=>setSocial({...social,platform:e.target.value})}/><input className='input' placeholder='URL' value={social.url} onChange={e=>setSocial({...social,url:e.target.value})}/></div><button className='btn primary' onClick={()=>{if(social.url)add('socialLinks',social);setSocial({platform:'Instagram',url:''})}}>Add Link</button></div><div className='rows'>{data.socialLinks.map((x:any,i:number)=><div className='row' key={i}><div><strong>{x.platform}</strong><small>{x.url}</small></div><span className='tag'>ACTIVE</span></div>)}</div></section>
   <section className='panel section'><div className='section-head'><div><div className='eyebrow'>SERVICES</div><h2>Services</h2><p>Showcase service names, descriptions and optional prices.</p></div></div><div className='form'><input className='input' placeholder='Service name' value={service.name} onChange={e=>setService({...service,name:e.target.value})}/><textarea className='input textarea' placeholder='Description' value={service.description} onChange={e=>setService({...service,description:e.target.value})}/><input className='input' type='number' placeholder='Price' value={service.price} onChange={e=>setService({...service,price:e.target.value})}/><button className='btn primary' onClick={()=>{if(service.name)add('services',{...service,price:service.price?Number(service.price):null});setService({name:'',description:'',price:''})}}>Add Service</button></div><div className='rows'>{data.services.map((x:any,i:number)=><div className='row' key={i}><div><strong>{x.name}</strong><small>{x.description||'Service'}</small></div><span className='tag'>{x.price!=null?'₹'+x.price:'—'}</span></div>)}</div></section>
  </section>
  <section className='grid'>
   <section className='panel section'><div className='section-head'><div><div className='eyebrow'>TESTIMONIALS</div><h2>Testimonials</h2><p>Customer quote cards with optional rating.</p></div></div><div className='form'><input className='input' placeholder='Customer name' value={testimonial.customer_name} onChange={e=>setTestimonial({...testimonial,customer_name:e.target.value})}/><textarea className='input textarea' placeholder='Quote' value={testimonial.quote} onChange={e=>setTestimonial({...testimonial,quote:e.target.value})}/><input className='input' type='number' min='1' max='5' value={testimonial.rating} onChange={e=>setTestimonial({...testimonial,rating:e.target.value})}/><button className='btn primary' onClick={()=>{if(testimonial.customer_name&&testimonial.quote)add('testimonials',{...testimonial,rating:Number(testimonial.rating)});setTestimonial({customer_name:'',quote:'',rating:'5'})}}>Add Testimonial</button></div><div className='rows'>{data.testimonials.map((x:any,i:number)=><div className='row' key={i}><div><strong>{x.customer_name}</strong><small>{x.quote}</small></div><span className='tag'>{x.rating||'—'}★</span></div>)}</div></section>
   <section className='panel section'><div className='section-head'><div><div className='eyebrow'>CONTACT + LEADS</div><h2>Lead Capture & Contact Form</h2><p>Toggle customer lead and contact forms on the public card.</p></div></div><div className='form'><label className='check'><input type='checkbox' checked={card.lead_capture_enabled} onChange={e=>setCard({...card,lead_capture_enabled:e.target.checked})}/> Enable Lead Capture Form</label><label className='check'><input type='checkbox' checked={card.contact_form_enabled} onChange={e=>setCard({...card,contact_form_enabled:e.target.checked})}/> Enable Contact Us Form</label><label className='field'><span>Payment URL</span><input className='input' value={card.payment_url} onChange={e=>setCard({...card,payment_url:e.target.value})} placeholder='https://payment.example/…'/></label><label className='field'><span>About Us</span><textarea className='input textarea' value={card.about_us} onChange={e=>setCard({...card,about_us:e.target.value})}/></label><label className='field'><span>Offline Content</span><textarea className='input textarea' value={card.offline_content} onChange={e=>setCard({...card,offline_content:e.target.value})}/></label><label className='field'><span>Embed Content</span><textarea className='input textarea' value={card.embed_content} onChange={e=>setCard({...card,embed_content:e.target.value})}/></label></div></section>
  </section>
  <div className='actions'><button className='btn primary' disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save Digital Card'}</button><span className='tag'>Unlimited contact methods</span><span className='tag'>Offline content</span><span className='tag'>Payment link</span></div>
 </div></AppShell>
}
