'use client';
import {useEffect,useState} from 'react';
import AppShell from '../components/AppShell';
import {getSupabase} from '../../../lib/supabase-browser';

type Category={id:string;name:string;description:string|null;active:boolean};
type Product={id:string;name:string;price:number;compare_at_price:number|null;stock_quantity:number;active:boolean;featured:boolean;description:string|null;category_id:string|null;catalog_categories?:{name:string}|null};
type Coupon={id:string;code:string;discount_type:string;discount_value:number;min_order_value:number;active:boolean};

const css=`
.page{display:grid;gap:14px}.hero{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;flex-wrap:wrap}.hero h1{margin:5px 0}.hero p{margin:0;color:#718096;font-size:11px;max-width:760px}
.tabs{display:flex;gap:4px;overflow:auto;background:#fff;border:1px solid #e1e8ec;border-radius:12px;padding:4px}.tab{padding:10px 13px;border-radius:9px;background:transparent;color:#667085;font-size:10px;font-weight:900;white-space:nowrap}.tab.active{background:#eef5ff;color:#2166d1}
.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:11px}.metric{padding:15px}.metric span{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.08em;color:#667085;font-weight:900}.metric strong{display:block;font-size:24px;margin-top:7px}.metric small{display:block;color:#88939c;font-size:9px;margin-top:3px}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.panel{min-width:0}.section{overflow:hidden}.section-head{display:flex;justify-content:space-between;gap:12px;padding:16px 18px;align-items:flex-start}.section-head h2{margin:4px 0 0;font-size:15px}.section-head p{margin:4px 0 0;color:#7d8992;font-size:9px}
.form{display:grid;gap:10px;padding:16px}.field{display:grid;gap:5px}.field span{font-size:8px;text-transform:uppercase;letter-spacing:.08em;color:#667085;font-weight:900}.input,.select{width:100%;border:1px solid #dce5e9;border-radius:9px;padding:10px 11px;background:#fff;font-size:10px}.textarea{min-height:72px;resize:vertical}
.actions{display:flex;gap:7px;flex-wrap:wrap}.btn{border:1px solid #dce5e9;border-radius:9px;padding:9px 11px;background:#fff;font-size:9px;font-weight:900;cursor:pointer}.primary{background:#2168c9;color:#fff;border-color:#2168c9}.soft{background:#eef5ff;color:#2166d1}.danger{color:#b42318;background:#fff7f6}.check{display:flex;gap:7px;align-items:center;font-size:9px;font-weight:800}
.list{padding:0 18px 12px}.row{display:grid;grid-template-columns:minmax(0,1fr) 110px 110px auto;gap:10px;align-items:center;padding:12px 0;border-top:1px solid #edf0f3}.row strong{font-size:10px}.row small{display:block;color:#88939c;font-size:8px;margin-top:3px}.tag{font-size:8px;font-weight:900;padding:5px 7px;border-radius:999px;background:#f3f5f6;color:#667085}.active{background:#edf9f1;color:#087443}.empty{padding:36px 20px;text-align:center;color:#667085;font-size:10px}
@media(max-width:950px){.grid{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:620px){.metrics{grid-template-columns:1fr}.row{grid-template-columns:1fr}}
`;

export default function CatalogPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[categories,setCategories]=useState<Category[]>([]),[products,setProducts]=useState<Product[]>([]),[coupons,setCoupons]=useState<Coupon[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const[categoryName,setCategoryName]=useState(''),[product,setProduct]=useState({name:'',price:'',compare_at_price:'',description:'',category_id:'',stock_quantity:'0',featured:false}),[coupon,setCoupon]=useState({code:'',discount_type:'percent',discount_value:'',min_order_value:'',max_uses:''});
 async function token(){const s=(await getSupabase().auth.getSession()).data.session;if(!s){location.href='/login';throw new Error('Session expired.')}return s.access_token}
 async function load(id:string){setLoading(true);setError('');try{const t=await token();const r=await fetch('/api/catalog?workspaceId='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+t},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to load catalogue.');setCategories(d.categories||[]);setProducts(d.products||[]);setCoupons(d.coupons||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load catalogue.')}finally{setLoading(false)}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);const onWorkspace=(e:Event)=>{const next=(e as CustomEvent<{workspaceId?:string}>).detail?.workspaceId||'';if(next&&next!==id){id=next;setWorkspaceId(next);void load(next)}};window.addEventListener('mdsm:workspace-changed',onWorkspace);if(id)void load(id);else setLoading(false);return()=>window.removeEventListener('mdsm:workspace-changed',onWorkspace)},[]);
 async function post(body:any){setBusy(body.type);setError('');try{const t=await token();const r=await fetch('/api/catalog',{method:'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({...body,workspaceId})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Save failed.');await load(workspaceId)}catch(e){setError(e instanceof Error?e.message:'Save failed.')}finally{setBusy('')}}
 async function toggle(type:string,id:string,current:boolean){setBusy(id);try{const t=await token();await fetch('/api/catalog',{method:'PATCH',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,type,id,active:!current})});await load(workspaceId)}catch(e){setError(e instanceof Error?e.message:'Update failed.')}finally{setBusy('')}}
 async function remove(type:string,id:string){if(!confirm('Remove this item from the workspace catalogue?'))return;setBusy(id);try{const t=await token();const r=await fetch('/api/catalog',{method:'DELETE',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,type,id})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Delete failed.');await load(workspaceId)}catch(e){setError(e instanceof Error?e.message:'Delete failed.')}finally{setBusy('')}}
 return <AppShell title='Product Catalogue'><style>{css}</style><div className='page'>
  <div className='hero'><div className='page-head'><div className='eyebrow'>PRODUCT CATALOGUE</div><h1>Products, Categories & Offers</h1><p>Workspace-scoped catalogue with unlimited categories and products. Cart and wishlist records are ready for the customer storefront.</p></div><div className='actions'><button className='btn soft' onClick={()=>location.href='/dashboard'}>← Dashboard</button></div></div>
  <div className='tabs'><button className='tab active'>Catalogue</button><button className='tab' onClick={()=>document.getElementById('coupons')?.scrollIntoView({behavior:'smooth'})}>Coupons & Offers</button><button className='tab' onClick={()=>location.href='/dashboard/digital-card'}>Digital Card</button></div>
  {error&&<div className='alert alert-error'>{error}</div>}
  <div className='metrics'><article className='panel metric'><span>Categories</span><strong>{loading?'—':categories.length}</strong><small>Unlimited supported</small></article><article className='panel metric'><span>Products</span><strong>{loading?'—':products.length}</strong><small>No 50-item cap</small></article><article className='panel metric'><span>Featured / Offers</span><strong>{loading?'—':products.filter(x=>x.featured||x.compare_at_price!=null).length}</strong><small>Hero-ready catalogue items</small></article><article className='panel metric'><span>Coupons</span><strong>{loading?'—':coupons.length}</strong><small>Percent or fixed discount</small></article></div>
  <div className='grid'>
   <section className='panel section'><div className='section-head'><div><div className='eyebrow'>CATEGORIES</div><h2>Unlimited Categories</h2><p>Create as many as your workspace needs.</p></div></div><div className='form'><input className='input' value={categoryName} onChange={e=>setCategoryName(e.target.value)} placeholder='Category name'/><button className='btn primary' disabled={!categoryName.trim()||busy==='category'} onClick={()=>{void post({type:'category',name:categoryName.trim()});setCategoryName('')}}>{busy==='category'?'Adding…':'Add Category'}</button></div><div className='list'>{categories.length?categories.map(x=><div className='row' key={x.id}><div><strong>{x.name}</strong><small>{x.description||'Catalogue category'}</small></div><span className={'tag '+(x.active?'active':'')}>{x.active?'ACTIVE':'PAUSED'}</span><button className='btn soft' onClick={()=>void toggle('category',x.id,x.active)}>{x.active?'Pause':'Activate'}</button><button className='btn danger' onClick={()=>void remove('category',x.id)}>Remove</button></div>):<div className='empty'>No categories yet.</div>}</div></section>
   <section className='panel section'><div className='section-head'><div><div className='eyebrow'>ADD PRODUCT</div><h2>Add Catalogue Product</h2><p>Product cards support price, offer price, stock and featured state.</p></div></div><div className='form'><label className='field'><span>Name</span><input className='input' value={product.name} onChange={e=>setProduct({...product,name:e.target.value})}/></label><label className='field'><span>Category</span><select className='select' value={product.category_id} onChange={e=>setProduct({...product,category_id:e.target.value})}><option value=''>No category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className='grid' style={{gridTemplateColumns:'1fr 1fr'}}><label className='field'><span>Price</span><input className='input' type='number' min='0' value={product.price} onChange={e=>setProduct({...product,price:e.target.value})}/></label><label className='field'><span>Offer / Compare Price</span><input className='input' type='number' min='0' value={product.compare_at_price} onChange={e=>setProduct({...product,compare_at_price:e.target.value})}/></label></div><label className='field'><span>Description</span><textarea className='input textarea' value={product.description} onChange={e=>setProduct({...product,description:e.target.value})}/></label><label className='field'><span>Stock</span><input className='input' type='number' min='0' value={product.stock_quantity} onChange={e=>setProduct({...product,stock_quantity:e.target.value})}/></label><label className='check'><input type='checkbox' checked={product.featured} onChange={e=>setProduct({...product,featured:e.target.checked})}/> Feature in hero / offers sections</label><button className='btn primary' disabled={!product.name.trim()||busy==='product'} onClick={()=>{void post({type:'product',...product});setProduct({name:'',price:'',compare_at_price:'',description:'',category_id:'',stock_quantity:'0',featured:false})}}>{busy==='product'?'Saving…':'Add Product'}</button></div></section>
  </div>
  <section className='panel section'><div className='section-head'><div><div className='eyebrow'>CATALOGUE</div><h2>Products</h2><p>Add to Cart and Wishlist tables are ready for the public storefront layer.</p></div></div><div className='list'>{products.length?products.map(x=><div className='row' key={x.id}><div><strong>{x.name}</strong><small>{x.catalog_categories?.name||'No category'} · {x.stock_quantity} in stock · {x.featured?'Featured':''}</small></div><span className='tag'>₹{Number(x.price||0).toFixed(2)}{x.compare_at_price!=null?' · Offer':''}</span><button className='btn soft' onClick={()=>void toggle('product',x.id,x.active)}>{x.active?'Pause':'Activate'}</button><button className='btn danger' onClick={()=>void remove('product',x.id)}>Remove</button></div>):<div className='empty'>No products yet.</div>}</div></section>
  <section id='coupons' className='panel section'><div className='section-head'><div><div className='eyebrow'>OFFERS & DISCOUNTS</div><h2>Coupon Codes</h2><p>Percent and fixed-value coupons with minimum-order and usage controls.</p></div></div><div className='form'><div className='grid' style={{gridTemplateColumns:'1fr 1fr'}}><label className='field'><span>Code</span><input className='input' value={coupon.code} onChange={e=>setCoupon({...coupon,code:e.target.value.toUpperCase()})}/></label><label className='field'><span>Discount Type</span><select className='select' value={coupon.discount_type} onChange={e=>setCoupon({...coupon,discount_type:e.target.value})}><option value='percent'>Percent</option><option value='fixed'>Fixed amount</option></select></label></div><div className='grid' style={{gridTemplateColumns:'1fr 1fr 1fr'}}><label className='field'><span>Discount</span><input className='input' type='number' min='0' value={coupon.discount_value} onChange={e=>setCoupon({...coupon,discount_value:e.target.value})}/></label><label className='field'><span>Minimum Order</span><input className='input' type='number' min='0' value={coupon.min_order_value} onChange={e=>setCoupon({...coupon,min_order_value:e.target.value})}/></label><label className='field'><span>Max Uses</span><input className='input' type='number' min='1' value={coupon.max_uses} onChange={e=>setCoupon({...coupon,max_uses:e.target.value})}/></label></div><button className='btn primary' disabled={!coupon.code.trim()||busy==='coupon'} onClick={()=>{void post({type:'coupon',...coupon});setCoupon({code:'',discount_type:'percent',discount_value:'',min_order_value:'',max_uses:''})}}>{busy==='coupon'?'Saving…':'Add Coupon Code'}</button></div><div className='list'>{coupons.length?coupons.map(x=><div className='row' key={x.id}><div><strong>{x.code}</strong><small>{x.discount_type==='percent'?x.discount_value+'% off':'₹'+x.discount_value+' off'} · Min ₹{x.min_order_value}</small></div><span className={'tag '+(x.active?'active':'')}>{x.active?'ACTIVE':'PAUSED'}</span><button className='btn soft' onClick={()=>void toggle('coupon',x.id,x.active)}> {x.active?'Pause':'Activate'} </button><button className='btn danger' onClick={()=>void remove('coupon',x.id)}>Remove</button></div>):<div className='empty'>No coupons yet.</div>}</div></section>
 </div></AppShell>
}
