'use client';

import {useEffect,useMemo,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

type Item={id:string;product_name:string;quantity:number;unit_price:number;line_total:number;sku:string|null};
type Order={id:string;order_number:string;customer_name:string;customer_email:string|null;customer_phone:string|null;subtotal:number;discount:number;total:number;coupon_code:string|null;status:string;payment_status:string;shipping_address:any;notes:string|null;created_at:string;items:Item[]};

const css='.page{display:grid;gap:14px}.head{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;flex-wrap:wrap}.head h1{margin:5px 0}.head p{margin:0;color:#73818b;font-size:10px}.actions{display:flex;gap:7px;flex-wrap:wrap}.btn{border:1px solid #dce5e9;border-radius:9px;padding:9px 11px;background:#fff;font-size:9px;font-weight:900;cursor:pointer}.primary{background:#2168c9;color:#fff;border-color:#2168c9}.notice{padding:10px 12px;background:#fff;border:1px solid #dce5e9;border-radius:10px;font-size:10px}.error{padding:10px 12px;background:#fff1f2;border:1px solid #f5c8cf;color:#9f1239;border-radius:10px;font-size:10px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.stat{padding:14px}.stat span{display:block;color:#77848d;font-size:8px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.stat strong{display:block;font-size:23px;margin-top:7px}.stat small{color:#8b969e;font-size:8px}.panel{overflow:hidden}.toolbar{display:flex;justify-content:space-between;gap:9px;align-items:center;padding:15px 17px;border-bottom:1px solid #edf0f3;flex-wrap:wrap}.search{width:280px;max-width:100%;padding:9px 10px;border:1px solid #dce5e9;border-radius:9px;font-size:10px}.filter{padding:9px 10px;border:1px solid #dce5e9;border-radius:9px;background:#fff;font-size:10px}.list{padding:0 17px 12px}.order{border-top:1px solid #edf0f3;padding:13px 0}.order:first-child{border-top:0}.top{display:grid;grid-template-columns:minmax(0,1fr) 100px 100px auto;gap:10px;align-items:center}.top strong{display:block;font-size:11px}.top small{display:block;color:#89959d;font-size:8px;margin-top:3px}.tag{display:inline-flex;padding:5px 7px;border-radius:999px;background:#f2f5f7;color:#66737d;font-size:8px;font-weight:900}.green{background:#edf9f1;color:#087443}.blue{background:#eef5ff;color:#2166d1}.orange{background:#fff7e9;color:#8b5e11}.items{margin:10px 0 0;padding-left:12px;border-left:2px solid #edf0f3;display:grid;gap:6px}.item{display:flex;justify-content:space-between;gap:10px;font-size:9px;color:#55636d}.item strong{color:#17202b}.order-actions{display:flex;gap:6px;margin-top:9px;flex-wrap:wrap}.empty{padding:40px 15px;text-align:center;color:#7c8891;font-size:10px}@media(max-width:900px){.stats{grid-template-columns:repeat(2,1fr)}.top{grid-template-columns:1fr 85px auto}}@media(max-width:650px){.stats{grid-template-columns:1fr 1fr}.top{grid-template-columns:1fr}.top .tag{width:max-content}}';

export default function CatalogOrdersPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState('');
 async function token(){const s=(await getSupabase().auth.getSession()).data.session;if(!s)throw new Error('Session expired');return s.access_token}
 async function load(id=workspaceId){if(!id)return;setLoading(true);setError('');try{const t=await token();const r=await fetch('/api/catalog/orders?workspaceId='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+t},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to load orders.');setOrders(d.orders||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load orders.')}finally{setLoading(false)}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);if(id)void load(id);else setLoading(false);const onWorkspace=(e:Event)=>{const next=(e as CustomEvent<{workspaceId?:string}>).detail?.workspaceId||'';if(next&&next!==id){id=next;setWorkspaceId(next);void load(next)}};window.addEventListener('mdsm:workspace-changed',onWorkspace);return()=>window.removeEventListener('mdsm:workspace-changed',onWorkspace)},[]);
 async function updateOrder(id:string,patch:any){setBusy(id);setNotice('');setError('');try{const t=await token();const r=await fetch('/api/catalog/orders',{method:'PATCH',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,id,...patch})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to update order.');setNotice('Order '+id.slice(0,8)+' updated.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update order.')}finally{setBusy('')}}
 const filtered=useMemo(()=>orders.filter(o=>{const q=query.toLowerCase().trim();const match=!q||[o.order_number,o.customer_name,o.customer_email,o.customer_phone].some(v=>String(v||'').toLowerCase().includes(q));return match&&(status==='all'||o.status===status)}),[orders,query,status]);
 const revenue=orders.reduce((n,o)=>n+Number(o.total||0),0),pending=orders.filter(o=>o.status==='pending').length,paid=orders.filter(o=>o.payment_status==='paid').length;
 return <AppShell title='Catalogue Orders'><style jsx>{css}</style><div className='page'>
  <div className='head'><div><div className='eyebrow'>PRODUCT CATALOGUE • ORDERS</div><h1>Orders & Checkout</h1><p>Real checkout orders from the public workspace catalogue. Payment stays pending until a payment provider is connected.</p></div><div className='actions'><button className='btn' onClick={()=>void load()}>↻ Refresh</button><button className='btn primary' onClick={()=>location.href='/dashboard/catalog'}>Catalogue →</button></div></div>
  {notice&&<div className='notice'>{notice}</div>}{error&&<div className='error'>{error}</div>}
  <div className='stats'><article className='panel stat'><span>Total Orders</span><strong>{loading?'—':orders.length}</strong><small>Workspace orders</small></article><article className='panel stat'><span>Pending</span><strong>{loading?'—':pending}</strong><small>Need action</small></article><article className='panel stat'><span>Paid</span><strong>{loading?'—':paid}</strong><small>Payment confirmed</small></article><article className='panel stat'><span>Order Value</span><strong>{loading?'—':'₹'+revenue.toFixed(2)}</strong><small>All recorded orders</small></article></div>
  <section className='panel'><div className='toolbar'><div><strong style={{fontSize:14}}>Workspace Orders</strong><div style={{marginTop:3,color:'#7d8992',fontSize:9}}>{filtered.length} matching order{filtered.length===1?'':'s'}</div></div><div className='actions'><input className='search' value={query} onChange={e=>setQuery(e.target.value)} placeholder='Search order, customer, phone…'/><select className='filter' value={status} onChange={e=>setStatus(e.target.value)}><option value='all'>All statuses</option><option value='pending'>Pending</option><option value='confirmed'>Confirmed</option><option value='processing'>Processing</option><option value='shipped'>Shipped</option><option value='delivered'>Delivered</option><option value='cancelled'>Cancelled</option></select></div></div>
  <div className='list'>{loading?<div className='empty'>Loading orders…</div>:filtered.length?filtered.map(o=><article className='order' key={o.id}><div className='top'><div><strong>{o.order_number} · {o.customer_name}</strong><small>{new Date(o.created_at).toLocaleString()} · {o.customer_email||o.customer_phone||'No contact detail'}</small></div><span className={'tag '+(o.status==='delivered'?'green':o.status==='processing'||o.status==='shipped'?'blue':o.status==='cancelled'?'orange':'')}>{o.status}</span><span className={'tag '+(o.payment_status==='paid'?'green':'')}>Payment: {o.payment_status}</span><strong>₹{Number(o.total||0).toFixed(2)}</strong></div><div className='items'>{o.items.map(i=><div className='item' key={i.id}><span><strong>{i.product_name}</strong> × {i.quantity}</span><span>₹{Number(i.line_total||0).toFixed(2)}</span></div>)}{o.discount>0&&<div className='item'><span>Discount {o.coupon_code?'('+o.coupon_code+')':''}</span><span>-₹{Number(o.discount).toFixed(2)}</span></div>}</div><div className='order-actions'><select className='filter' value={o.status} disabled={busy===o.id} onChange={e=>void updateOrder(o.id,{status:e.target.value})}>{['pending','confirmed','processing','shipped','delivered','cancelled'].map(x=><option key={x} value={x}>{x}</option>)}</select><select className='filter' value={o.payment_status} disabled={busy===o.id} onChange={e=>void updateOrder(o.id,{payment_status:e.target.value})}>{['pending','paid','failed','refunded'].map(x=><option key={x} value={x}>{x}</option>)}</select></div></article>):<div className='empty'>No catalogue orders yet. Public checkout orders will appear here automatically.</div>}</div></section>
 </div></AppShell>
}