'use client';

import { useEffect, useState } from 'react';
import { getSupabase } from '../../lib/supabase-browser';

export default function DashboardPage() {
  const [email, setEmail] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { try { getSupabase().auth.getUser().then(({ data, error }) => { if (error) setError(error.message); else if (!data.user) window.location.href = '/login'; else setEmail(data.user.email ?? ''); setLoading(false); }); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to connect to Supabase.'); setLoading(false); } }, []);
  async function signOut() { try { await getSupabase().auth.signOut(); } finally { window.location.href = '/login'; } }
  if (loading) return <main className="auth-page"><div className="muted">Loading workspace…</div></main>;
  if (error) return <main className="auth-page"><section className="auth-card"><div className="brand">MD HYGIENE</div><h1>Configuration needed</h1><p className="muted">{error}</p></section></main>;
  return <main className="dashboard"><header className="topbar"><div><div className="brand">MD HYGIENE</div><strong>Social Media Manager</strong></div><button className="secondary" onClick={signOut}>Sign out</button></header><section className="workspace"><div className="workspace-head"><div><span className="eyebrow">WORKSPACE</span><h1>Good to see you 👋</h1><p className="muted">Manage your social presence from one clean workspace.</p></div><span className="status">● All systems ready</span></div><div className="cards"><article><span>📘</span><h2>Facebook Pages</h2><p>Connect and manage multiple Facebook Pages.</p><button className="secondary" onClick={() => window.location.href = '/dashboard/accounts'}>Manage Accounts</button><button className="secondary" style={{ marginLeft: 8 }} onClick={() => window.location.href = '/dashboard/publish'}>Create Post</button></article><article><span>📸</span><h2>Instagram</h2><p>Connect and manage professional Instagram accounts.</p><button className="secondary" onClick={() => window.location.href = '/dashboard/accounts'}>Manage Accounts</button></article><article><span>📍</span><h2>Google Business</h2><p>Manage multiple Google Business locations in one place.</p><button className="secondary" onClick={() => window.location.href = '/dashboard/accounts'}>Manage Accounts</button></article></div><section style={{marginTop:24,display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:18}}><article style={{background:'#fff',border:'1px solid #e7ebf1',borderRadius:22,padding:22,boxShadow:'0 12px 35px rgba(15,23,42,.055)'}}><span className="eyebrow">CONNECTED</span><h2 style={{margin:'9px 0 4px'}}>Accounts</h2><p className="muted">Keep every connected channel in one place.</p><button className="secondary" onClick={() => window.location.href='/dashboard/accounts'}>Open Accounts →</button></article><article style={{background:'#fff',border:'1px solid #e7ebf1',borderRadius:22,padding:22,boxShadow:'0 12px 35px rgba(15,23,42,.055)'}}><span className="eyebrow">CONTENT</span><h2 style={{margin:'9px 0 4px'}}>Publish Center</h2><p className="muted">Write, preview and publish your next post.</p><button className="secondary" onClick={() => window.location.href='/dashboard/publish'}>Create Post →</button></article><article style={{background:'#fff',border:'1px solid #e7ebf1',borderRadius:22,padding:22,boxShadow:'0 12px 35px rgba(15,23,42,.055)'}}><span className="eyebrow">ACCOUNT</span><h2 style={{margin:'9px 0 4px'}}>Signed in</h2><p className="muted">{email}</p><span className="status">● Active session</span></article></section></section></main>;
}
