'use client';
import { useEffect, useState } from 'react';
import { getSupabase } from '../../lib/supabase-browser';

const nav=[['Dashboard','⌂','/dashboard'],['Accounts','◎','/dashboard/accounts'],['Create Post','✎','/dashboard/publish'],['Calendar','□','/dashboard/calendar'],['Analytics','▥','/dashboard/analytics'],['Media Library','▧','/dashboard/media'],['Leads','♙','/dashboard/leads'],['Settings','⚙','/dashboard/settings']];
type Metrics={source:string;fetchedAt:string;accounts:{id:string;platform:string;name:string;handle:string|null}[];stats:{totalPosts:number|null;reach:number|null;engagement:number|null;followers:number|null;trackedPublished:number};recentPosts:{id:string;platform:string;title:string;date:string;url:string|null;reach:number|null;engagement:number|null}[];warnings:string[]};

function formatNumber(value:number|null){if(value===null)return '—';if(value>=1000000)return `${(value/1000000).toFixed(1)}M`;if(value>=1000)return `${(value/1000).toFixed(value>=10000?0:1)}K`;return value.toLocaleString();}
function formatDate(value:string){return new Date(value).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});}

export default function DashboardPage(){
 const[email,setEmail]=useState(''),[loading,setLoading]=useState(true),[metrics,setMetrics]=useState<Metrics|null>(null),[error,setError]=useState(''),[mobileNav,setMobileNav]=useState(false),[refreshing,setRefreshing]=useState(false);
 useEffect(()=>{getSupabase().auth.getUser().then(async({data,error})=>{if(error)setError(error.message);else if(!data.user){location.href='/login';return}else{setEmail(data.user.email||'');await loadMetrics()}setLoading(false)})},[]);
 async function loadMetrics(){try{setRefreshing(true);setError('');const session=(await getSupabase().auth.getSession()).data.session;if(!session){location.href='/login';return}const response=await fetch('/api/dashboard/metrics',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load live metrics.');setMetrics(data)}catch(e){setError(e instanceof Error?e.message:'Unable to load live metrics.')}finally{setRefreshing(false)}}
 async function signOut(){await getSupabase().auth.signOut();location.href='/login'}
 function go(href:string){location.href=href;setMobileNav(false)}
 if(loading)return <main className="auth-page"><div className="muted">Loading live workspace…</div></main>;
 if(error&&!metrics)return <main className="auth-page"><section className="auth-card"><div className="brand">MD HYGIENE</div><h1>Live data unavailable</h1><p className="muted">{error}</p><button className="primary-btn" onClick={loadMetrics}>Retry</button></section></main>;
 const stats=[['Total Posts',metrics?.stats.totalPosts,'Meta account totals','↗'],['Total Reach',metrics?.stats.reach,'Last 28 days','◉'],['Engagement',metrics?.stats.engagement,'Last 28 days','♡'],['Followers',metrics?.stats.followers,'Current total','♧'],['Tracked Posts',metrics?.stats.trackedPublished,'Published by this app','➤']];
 return <main className="app-shell"><button className={`mobile-nav-backdrop ${mobileNav?'show':''}`} aria-label="Close navigation" onClick={()=>setMobileNav(false)}/><aside className={`sidebar ${mobileNav?'mobile-open':''}`}><div className="logo-block"><div className="logo-mark">MD</div><div className="logo-title">MD<span>HYGIENE</span><small>SOCIAL MANAGER</small></div><button className="mobile-close" onClick={()=>setMobileNav(false)}>×</button></div><nav>{nav.map(([label,icon,href])=><button key={label} className={`nav-item ${label==='Dashboard'?'active':''}`} onClick={()=>go(href)}><b>{icon}</b><span>{label}</span></button>)}</nav><div className="plan-card"><div className="plan-icon">➤</div><strong>Professional Plan</strong><small>Valid till 23 Dec 2026</small><button onClick={()=>go('/dashboard/settings')}>Manage Plan</button></div><div className="side-user"><div className="user-avatar">MD</div><div><strong>MD Hygiene</strong><small>{email||'Admin'}</small></div><button onClick={signOut}>↪</button></div></aside><section className="main-shell"><header className="main-header"><button className="menu-btn" onClick={()=>setMobileNav(true)}>☰</button><strong>Dashboard</strong><div className="search-box">⌕ <span>Search anything...</span><kbd>Ctrl K</kbd></div><div className="header-actions"><button aria-label="Refresh live data" onClick={loadMetrics}>{refreshing?'…':'↻'}</button><button className="header-profile" onClick={()=>go('/dashboard/settings')}><div className="mini-logo">MD</div><strong>MD Hygiene</strong><span>⌄</span></button></div></header><div className="dashboard-content"><div className="welcome-row"><div><h1>Welcome back, MD Hygiene! 👋</h1><p>Live social metrics from your connected Meta accounts.</p></div><span className="live-pill"><i/> {metrics?.source==='meta_graph_api'?'Live Meta Data':'No live source'}</span></div>
 <div className="stat-grid">{stats.map(([name,value,change,icon])=><article className="stat-card" key={name as string}><div className="stat-icon">{icon}</div><div><span>{name}</span><strong>{formatNumber(value as number|null)}</strong><small>{change}</small></div></article>)}</div>
 {metrics?.warnings?.length?<div className="data-warning">Some Meta metrics are unavailable because the connected account does not grant that insight permission. No placeholder numbers are shown.</div>:null}
 <div className="channel-grid">{metrics?.accounts.length?metrics.accounts.map(account=><Channel key={account.id} platform={account.platform} title={account.platform==='instagram'?'Instagram':'Facebook'} subtitle={account.platform==='instagram'?'Instagram Business Account':'Facebook Page'} name={account.name} detail={account.handle?`@${account.handle}`:'Connected'} tone={account.platform==='instagram'?'pink':'blue'} action="Manage Account" href="/dashboard/accounts"/>):<div className="empty-card"><strong>No social accounts connected</strong><span>Connect Facebook or Instagram to load real metrics.</span><button onClick={()=>go('/dashboard/accounts')}>Connect Account</button></div>}</div>
 <div className="bottom-grid"><section className="recent-card"><div className="section-head"><div><span>LIVE CONTENT</span><h2>Recent Posts</h2></div><button onClick={()=>go('/dashboard/calendar')}>View all</button></div>{metrics?.recentPosts.length?metrics.recentPosts.map((p,i)=><div className="post-row" key={p.id}><div className={`post-thumb thumb-${i%4}`}>{p.platform==='Instagram'?'◎':'f'}</div><div className="post-title"><strong>{p.title}</strong><small>{p.platform} · {formatDate(p.date)}</small></div><span>{formatNumber(p.reach)}</span><span>{formatNumber(p.engagement)}</span><em>Live</em><b>⋮</b></div>):<div className="empty-state"><strong>No recent posts returned by Meta.</strong><span>Publish a post or reconnect the account to see live content here.</span></div>}</section><aside className="right-column"><div className="quick-card"><span className="quick-icon">✎</span><div><strong>Quick Create Post</strong><small>Create and publish new post across connected platforms</small></div><button onClick={()=>go('/dashboard/publish')}>＋ Create New Post</button></div><div className="summary-card"><div className="section-head"><div><span>LIVE OVERVIEW</span><h2>Current Metrics</h2></div><button className="text-btn" onClick={loadMetrics}>{refreshing?'Updating…':'Refresh'}</button></div><Summary label="Total Posts" value={formatNumber(metrics?.stats.totalPosts??null)}/><Summary label="Total Reach" value={formatNumber(metrics?.stats.reach??null)}/><Summary label="Engagement" value={formatNumber(metrics?.stats.engagement??null)}/><Summary label="Followers" value={formatNumber(metrics?.stats.followers??null)}/></div></aside></div></div></section></main>}

function Channel({platform,title,subtitle,name,detail,tone,action,href}:{platform:string;title:string;subtitle:string;name:string;detail:string;tone:string;action:string;href:string}){return <article className="channel-card"><div className={`channel-icon ${tone}`}>{platform==='instagram'?'◎':'f'}</div><div className="channel-head"><div><h2>{title}</h2><small>{subtitle}</small></div><span className="connected-pill">✓ Connected</span></div><div className="channel-account"><div className="mini-logo">MD</div><div><strong>{name}</strong><small>{detail}</small></div></div><button className={`channel-action ${tone}`} onClick={()=>location.href=href}>{action}<b>›</b></button></article>}
function Summary({label,value}:{label:string;value:string}){return <div className="summary-row"><span>◉</span><strong>{label}</strong><b>{value}</b></div>}
