'use client';
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

export default function AIReviewFormPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[exists,setExists]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function check(id:string){try{const r=await getSupabase().from('feedback_forms').select('id,name').eq('workspace_id',id).ilike('name','%Custom AI Review Suggestion%').limit(1).maybeSingle();if(r.error)throw r.error;setExists(Boolean(r.data))}catch(e){setError(e instanceof Error?e.message:'Unable to check AI form.')}}
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);if(id)void check(id)},[]);
 async function create(){setBusy(true);setError('');setMessage('');try{if(!workspaceId)throw Error('Select a workspace first.');const sb=getSupabase(),s=(await sb.auth.getSession()).data.session;if(!s)throw Error('Session expired.');const a=await fetch('/api/workspace-access?workspace_id='+encodeURIComponent(workspaceId),{headers:{Authorization:'Bearer '+s.access_token},cache:'no-store'});const ad=await a.json();if(!a.ok||(!ad?.is_owner_or_admin&&!['owner','admin','manager'].includes(String(ad?.effectiveRole||'').toLowerCase())))throw Error('Only a workspace manager can create the AI form.');const now=new Date().toISOString();const payload={workspace_id:workspaceId,name:'Custom AI Review Suggestion Form',slug:'custom-ai-review-suggestion',title:'Tell us about your experience',description:'Structured feedback for an AI-assisted response draft. The customer-facing response remains editable and approval-first.',fields:[{id:crypto.randomUUID(),label:'Overall rating',type:'rating',required:true},{id:crypto.randomUUID(),label:'What went well?',type:'textarea',required:false},{id:crypto.randomUUID(),label:'What could we improve?',type:'textarea',required:false},{id:crypto.randomUUID(),label:'Anything else?',type:'textarea',required:false}],active:true,ai_enabled:true,created_at:now,updated_at:now};const r=await sb.from('feedback_forms').insert(payload);if(r.error)throw r.error;setExists(true);setMessage('Custom AI Review Suggestion Form created.')}catch(e){setError(e instanceof Error?e.message:'Unable to create AI review form.')}finally{setBusy(false)}}
 return <AppShell title='Custom AI Review Suggestion Form'><style jsx>{".page{display:grid;gap:14px}.panel{padding:18px}.hero h1{margin:5px 0}.note{font-size:10px;color:#667085;line-height:1.6}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{border:1px solid #dbe4e8;background:#fff;border-radius:9px;padding:9px 11px;font-size:9px;font-weight:900;cursor:pointer}.primary{background:#087f7b;color:#fff;border-color:#087f7b}"} </style><div className='page'><section className='panel hero'><div className='eyebrow'>CUSTOM AI FORM</div><h1>Custom AI Review Suggestion Form</h1><p className='note'>Create a ready-made AI-enabled structured feedback form, then customize it from Feedback Forms.</p></section>{error&&<div className='alert alert-error'>{error}</div>}{message&&<div className='alert alert-success'>{message}</div>}<section className='panel'><h2 style={{margin:'0 0 5px'}}>AI review form preset</h2><p className='note'>{exists?'The preset already exists for this workspace.':'Create it once and customize later.'}</p><div className='actions' style={{marginTop:10}}><button className='btn primary' disabled={busy||exists} onClick={()=>void create()}>{exists?'Already Created':busy?'Creating…':'Create AI Review Suggestion Form'}</button><button className='btn' onClick={()=>location.href='/dashboard/gmb/forms'}>Customize Form →</button><button className='btn' onClick={()=>location.href='/dashboard/gmb/responses'}>View AI Responses →</button></div></section></div></AppShell>
}
