'use client';
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';

type Review={id:string;reviewer_name:string|null;rating:number|null;comment:string|null;review_time:string|null};
type ImageRow={id:string;review_id:string|null;image_url:string;template:string|null;created_at:string};

const css='.page{display:grid;gap:16px}.topbar{display:flex;justify-content:space-between;gap:12px;align-items:end;flex-wrap:wrap}.select{border:1px solid #dbe4e8;border-radius:10px;padding:10px 12px;background:#fff;min-width:260px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.card{padding:14px;overflow:hidden}.preview{width:100%;aspect-ratio:4/3;display:block;object-fit:cover;border:1px solid #e6ecee;border-radius:11px;background:#f7fbfa}.meta{display:grid;gap:5px;margin-top:10px}.muted{color:#667085;font-size:10px;line-height:1.5}.actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.empty{padding:40px;text-align:center;color:#667085;font-size:11px}@media(max-width:950px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.grid{grid-template-columns:1fr}}';
export default function ReviewImagesPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[reviews,setReviews]=useState<Review[]>([]),[images,setImages]=useState<ImageRow[]>([]),[reviewId,setReviewId]=useState(''),[template,setTemplate]=useState('clean'),[canManage,setCanManage]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function load(id:string){
  setLoading(true);setError('');
  try{const sb=getSupabase(),s=(await sb.auth.getSession()).data.session;const[r,i,a]=await Promise.all([sb.from('google_business_reviews').select('id,reviewer_name,rating,comment,review_time').eq('workspace_id',id).order('review_time',{ascending:false}).limit(100),sb.from('review_images').select('id,review_id,image_url,template,created_at').eq('workspace_id',id).order('created_at',{ascending:false}).limit(100),fetch('/api/workspace-access?workspace_id='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+(s?.access_token||'')},cache:'no-store'})]);if(r.error)throw r.error;if(i.error)throw i.error;setReviews((r.data||[]) as Review[]);setImages((i.data||[]) as ImageRow[]);setReviewId(v=>v||String((r.data||[])[0]?.id||''));const d=await a.json().catch(()=>({}));setCanManage(Boolean(d?.is_owner_or_admin||['owner','admin','manager'].includes(String(d?.effectiveRole||'').toLowerCase())))}catch(e){setError(e instanceof Error?e.message:'Unable to load review images.')}finally{setLoading(false)}
 }
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);const onWorkspace=(event:Event)=>{const next=(event as CustomEvent<{workspaceId?:string}>).detail?.workspaceId||'';if(next&&next!==id){id=next;setWorkspaceId(next);void load(next);}};window.addEventListener('mdsm:workspace-changed',onWorkspace);if(id)void load(id);else setLoading(false);return()=>window.removeEventListener('mdsm:workspace-changed',onWorkspace)},[]);
 async function createImage(){setBusy('create');setError('');try{const s=(await getSupabase().auth.getSession()).data.session;const r=await fetch('/api/google/business/review-image',{method:'POST',headers:{Authorization:'Bearer '+(s?.access_token||''),'Content-Type':'application/json'},body:JSON.stringify({reviewId,template})});const d=await r.json();if(!r.ok)throw Error(d?.error||'Unable to create image.');setImages(v=>[d.image,...v])}catch(e){setError(e instanceof Error?e.message:'Unable to create image.')}finally{setBusy('')}}
 const reviewMap=new Map(reviews.map(x=>[x.id,x]));
 return <AppShell title='Google Business & Reviews'><style>{css}</style><div className='page'><div className='page-head'><div><div className='eyebrow'>AI GOOGLE REVIEW IMAGE</div><h1>Review Image Generator</h1><p>Turn a real imported Google review into a shareable social card. The original review text and rating remain unchanged.</p></div></div>{error&&<div className='alert alert-error'>{error}</div>}<section className='panel' style={{padding:20}}><div className='topbar'><div><div className='eyebrow'>CREATE IMAGE</div><h2 style={{margin:'5px 0'}}>Choose a review</h2><div className='muted'>AI may create a short headline when configured; the customer review itself is preserved.</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><select className='select' value={reviewId} onChange={e=>setReviewId(e.target.value)}><option value=''>Select review</option>{reviews.map(x=><option key={x.id} value={x.id}>{x.reviewer_name||'Customer'} · {x.rating||'—'}★ · {(x.comment||'').slice(0,45)}</option>)}</select><select className='select' style={{minWidth:140}} value={template} onChange={e=>setTemplate(e.target.value)}><option value='clean'>Clean</option><option value='minimal'>Minimal</option></select><button className='btn btn-primary' disabled={!canManage||!reviewId||busy==='create'} onClick={()=>void createImage()}>{busy==='create'?'Creating…':'✦ Create Image'}</button></div></div></section><section className='panel'><div className='panel-head'><div><div className='eyebrow'>IMAGE LIBRARY</div><h2>Generated review cards</h2></div></div>{loading?<div className='empty'>Loading…</div>:!images.length?<div className='empty'>No review images yet.</div>:<div className='grid' style={{padding:'0 18px 18px'}}>{images.map(x=>{const r=reviewMap.get(x.review_id||'');return <article className='panel card' key={x.id}><img className='preview' src={x.image_url} alt='Generated Google review card'/><div className='meta'><div className='muted'><strong>{r?.reviewer_name||'Review'}</strong> · {r?.rating||'—'}★ · {x.template||'clean'}</div><div className='muted'>{new Date(x.created_at).toLocaleDateString()}</div></div><div className='actions'><a className='btn btn-soft' href={x.image_url} target='_blank' rel='noreferrer'>Open Image</a><a className='btn btn-soft' href={x.image_url} download='google-review-card.svg'>Save Image</a></div></article>})}</div>}</section></div></AppShell>
}
