'use client';
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {getSupabase} from '../../../../lib/supabase-browser';
type Review={id:string;reviewer_name:string|null;rating:number|null;comment:string|null};
export default function ImagesPage(){
 const[workspaceId,setWorkspaceId]=useState(''),[reviews,setReviews]=useState<Review[]>([]),[selected,setSelected]=useState(''),[business,setBusiness]=useState('Business Name'),[downloaded,setDownloaded]=useState(false),[error,setError]=useState('');
 const current=reviews.find(x=>x.id===selected)||reviews[0];
 useEffect(()=>{let id='';try{id=localStorage.getItem('mdsm:selectedWorkspaceId')||''}catch{}setWorkspaceId(id);if(id){(async()=>{const sb=getSupabase();const [r,p]=await Promise.all([sb.from('google_business_reviews').select('id,reviewer_name,rating,comment').eq('workspace_id',id).order('review_time',{ascending:false}).limit(50),sb.from('google_business_profiles').select('business_name').eq('workspace_id',id).order('business_name').limit(1)]);if(r.error)throw r.error;if(p.error)throw p.error;setReviews((r.data||[]) as Review[]);if(r.data?.[0])setSelected(r.data[0].id);if(p.data?.[0])setBusiness(p.data[0].business_name)})().catch(e=>setError(e instanceof Error?e.message:'Unable to load reviews.'))}},[]);
 function download(){if(!current)return;const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=900;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.fillStyle='#087f7b';ctx.fillRect(0,0,1200,900);ctx.fillStyle='#ffffff';ctx.font='800 36px system-ui';ctx.fillText(business,80,100);ctx.font='900 76px system-ui';ctx.fillText('★'.repeat(Math.max(0,current.rating||5)),80,220);ctx.font='700 48px system-ui';ctx.fillText('Customer Review',80,300);const text=String(current.comment||'Rating only').slice(0,320);ctx.font='500 38px system-ui';const words=text.split(' ');let line='',y=390;for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>1040){ctx.fillText(line,80,y);line=word;y+=55;if(y>720)break}else line=test}if(line&&y<=720)ctx.fillText(line,80,y);ctx.font='700 30px system-ui';ctx.fillText('— '+(current.reviewer_name||'Google customer'),80,800);canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='review-'+current.id+'.png';a.click();URL.revokeObjectURL(a.href);setDownloaded(true)})}
 return <AppShell title='Google Business & Reviews'><style jsx>{`.page{display:grid;gap:16px}.form{padding:20px;display:grid;gap:12px}.field{display:grid;gap:6px}.field label{font-size:10px;font-weight:850;color:#475467}.field select,.field input{border:1px solid #dbe4e8;border-radius:10px;padding:11px 12px;background:#fff}.preview{display:grid;place-items:center;padding:28px;background:#0f172a;border-radius:16px}.card{width:min(720px,100%);aspect-ratio:4/3;background:#087f7b;color:#fff;border-radius:18px;padding:48px;box-sizing:border-box;display:flex;flex-direction:column;justify-content:center;box-shadow:0 24px 60px rgba(15,23,42,.22)}.card .brand{font-size:18px;font-weight:850}.card .stars{font-size:46px;margin:22px 0}.card .quote{font-size:26px;line-height:1.4;font-weight:600}.card .name{margin-top:30px;font-size:16px}.empty{padding:40px;text-align:center;color:#667085}@media(max-width:700px){.card{padding:28px}.card .quote{font-size:18px}.card .stars{font-size:32px}}`}</style><div className='page'><div className='page-head'><div><div className='eyebrow'>REVIEW IMAGE GENERATOR</div><h1>Review Quote Images</h1><p>Create a clean shareable image from a real imported Google review. Nothing is invented.</p></div></div>{error&&<div className='alert alert-error'>{error}</div>}{reviews.length===0?<section className='panel empty'>Import Google reviews first, then choose a review to create an image.</section>:<><section className='panel form'><div className='field'><label>Review</label><select value={selected} onChange={e=>setSelected(e.target.value)}>{reviews.map(r=><option key={r.id} value={r.id}>{r.reviewer_name||'Google customer'} · {r.rating||'—'} stars</option>)}</select></div><div><button className='btn btn-primary' onClick={download}>Download PNG</button>{downloaded&&<span style={{marginLeft:10,fontSize:10,color:'#14804a',fontWeight:800}}>Image created.</span>}</div></section><section className='panel preview'><div className='card'><div className='brand'>{business}</div><div className='stars'>{current?.rating?'★'.repeat(current.rating):'★★★★★'}</div><div className='quote'>“{current?.comment||'Rating only' }”</div><div className='name'>— {current?.reviewer_name||'Google customer'}</div></div></section></>}</div></AppShell>
}